import type { SeedWord } from "./seed-words.types.js";

export const SR_WORDS: SeedWord[] = [
  // Place (1)
  {
    language: "es",
    conceptKey: "nightclub",
    word: "boliche",
    translationRu: "ночной клуб",
    type: "Place",
    rarity: "SR",
    baseAtk: 65,
    baseDef: 55,
    colorido: 5,
    flavorText: "El boliche estaba lleno y la música sonaba fuerte.",
    hint: "«Boliche» напоминает боулинг и неон — место для ночных развлечений, клуб.",
    tags: ["slang", "salidas"],
    quizCorrect: "ночной клуб",
    quizOptions: ["ночной клуб", "офис", "станция", "больница"],
  },

  // Person (1)
  {
    language: "es",
    conceptKey: "kid_slang",
    word: "pibe",
    translationRu: "парень (разг.)",
    type: "Person",
    rarity: "SR",
    baseAtk: 70,
    baseDef: 45,
    colorido: 5,
    flavorText: "Ese pibe juega al fútbol como si nada.",
    hint: "«Pibe» звучит коротко и дерзко, как оклик пацану: парень.",
    tags: ["slang", "conversación"],
    quizCorrect: "парень (разг.)",
    quizOptions: ["парень (разг.)", "начальник", "незнакомец", "гость"],
  },

  // Actions (2)
  {
    language: "es",
    conceptKey: "realize",
    word: "darse cuenta",
    translationRu: "понимать (вдруг)",
    type: "Action",
    rarity: "SR",
    baseAtk: 60,
    baseDef: 65,
    colorido: 5,
    flavorText: "Me di cuenta tarde de que era una broma.",
    hint: "«Darse cuenta» — будто дать себе отчёт: внезапно понять.",
    tags: ["idioma", "verbo"],
    quizCorrect: "понимать (вдруг)",
    quizOptions: ["понимать (вдруг)", "убеждать", "воспользоваться", "узнавать"],
  },
  {
    language: "es",
    conceptKey: "support_slang",
    word: "bancar",
    translationRu: "поддерживать (разг.)",
    type: "Action",
    rarity: "SR",
    baseAtk: 70,
    baseDef: 55,
    colorido: 5,
    flavorText: "Te banco, pero esta vez te fuiste de tema.",
    hint: "«Bancar» — как банк, который держит тебя на плаву: поддерживать.",
    tags: ["slang", "conversación"],
    quizCorrect: "поддерживать (разг.)",
    quizOptions: ["поддерживать (разг.)", "ждать", "звонить", "покупать"],
  },

  // Object (1)
  {
    language: "es",
    conceptKey: "mess_slang",
    word: "quilombo",
    translationRu: "бардак",
    type: "Object",
    rarity: "SR",
    baseAtk: 75,
    baseDef: 55,
    colorido: 5,
    flavorText: "Se armó un quilombo en la calle por un choque.",
    hint: "«Quilombo» звучит как грохот и крик — полный бардак.",
    tags: ["slang", "ciudad"],
    quizCorrect: "бардак",
    quizOptions: ["бардак", "подарок", "карта", "возможность"],
  },

  // Emotion (1)
  {
    language: "es",
    conceptKey: "nostalgia",
    word: "nostalgia",
    translationRu: "ностальгия",
    type: "Emotion",
    rarity: "SR",
    baseAtk: 55,
    baseDef: 70,
    colorido: 4,
    flavorText: "Me agarró nostalgia cuando escuché esa canción.",
    hint: "«Nostalgia» почти не меняется между языками — ностальгия.",
    tags: ["emociones", "cultura"],
    quizCorrect: "ностальгия",
    quizOptions: ["ностальгия", "радость", "страх", "облегчение"],
  },

  // Expressions (4)
  {
    language: "es",
    conceptKey: "carry_responsibility",
    word: "cargar con",
    translationRu: "нести ответственность за",
    type: "Action",
    rarity: "SR",
    baseAtk: 65,
    baseDef: 65,
    colorido: 5,
    flavorText: "No quiero cargar con todo yo solo.",
    hint: "«Cargar con» — как тащить груз на себе, то есть нести ответственность за.",
    tags: ["idioma", "formal"],
    quizCorrect: "нести ответственность за",
    quizOptions: ["нести ответственность за", "убеждать", "воспользоваться", "ждать"],
  },
  {
    language: "es",
    conceptKey: "daydream",
    word: "estar en las nubes",
    translationRu: "витать в облаках",
    type: "Expression",
    rarity: "SR",
    baseAtk: 55,
    baseDef: 60,
    colorido: 5,
    flavorText: "Perdón, estaba en las nubes y no escuché tu pregunta.",
    hint: "«Estar en las nubes» — будто сидишь в облаках, значит витать в облаках.",
    tags: ["idioma", "conversación"],
    quizCorrect: "витать в облаках",
    quizOptions: ["витать в облаках", "быть злым", "быть уставшим", "быть голодным"],
  },
  {
    language: "es",
    conceptKey: "no_problem",
    word: "no hay drama",
    translationRu: "нет проблем",
    type: "Expression",
    rarity: "SR",
    baseAtk: 60,
    baseDef: 55,
    colorido: 5,
    flavorText: "—Perdón por la demora. —No hay drama, tranqui.",
    hint: "«No hay drama» — драмы нет, значит нет проблем.",
    tags: ["slang", "conversación"],
    quizCorrect: "нет проблем",
    quizOptions: ["нет проблем", "ни за что", "вдруг", "доброе утро"],
  },
  {
    language: "es",
    conceptKey: "no_way_slang",
    word: "ni en pedo",
    translationRu: "ни за что (жёстко)",
    type: "Expression",
    rarity: "SR",
    baseAtk: 70,
    baseDef: 50,
    colorido: 5,
    flavorText: "Ni en pedo voy a pagar eso, es un robo.",
    hint: "«Ni en pedo» — даже в пьяном угаре нет: ни за что.",
    tags: ["slang", "conversación"],
    quizCorrect: "ни за что (жёстко)",
    quizOptions: ["ни за что (жёстко)", "пожалуйста", "не за что", "как дела?"],
  },
];

