import { prisma } from "../src/db/prisma.js";
import { STARTING_DUST } from "../src/shared/constants.js";

type SeedWord = {
  language: "es";
  word: string;
  translationRu: string;
  type: "Person" | "Place" | "Action" | "Object" | "Emotion" | "Expression";
  rarity: "C" | "UC" | "R" | "SR";
  baseAtk: number;
  baseDef: number;
  colorido: number;
  flavorText: string;
  hint: string;
  tags: string[];
  canEvolve?: boolean;
  imagePrompt?: string | null;
  quizCorrect: string;
  quizOptions: [string, string, string, string];
  evolutionData?: unknown | null;
};

const WORDS: SeedWord[] = [
  // C (15)
  {
    language: "es",
    word: "casa",
    translationRu: "дом",
    type: "Place",
    rarity: "C",
    baseAtk: 40,
    baseDef: 60,
    colorido: 2,
    flavorText: "—¿Dónde vivís? —En casa de mis viejos, por ahora.",
    hint: "Базовое слово: 'дом'. Часто встречается в первых уроках.",
    tags: ["básico", "vivienda"],
    quizCorrect: "дом",
    quizOptions: ["дом", "машина", "улица", "город"],
  },
  {
    language: "es",
    word: "escuela",
    translationRu: "школа",
    type: "Place",
    rarity: "C",
    baseAtk: 35,
    baseDef: 55,
    colorido: 2,
    flavorText: "Mi hermana va a la escuela temprano.",
    hint: "Слово женского рода; часто употребляется с артиклем 'la'.",
    tags: ["básico", "educación"],
    quizCorrect: "школа",
    quizOptions: ["школа", "работа", "магазин", "парк"],
  },
  {
    language: "es",
    word: "calle",
    translationRu: "улица",
    type: "Place",
    rarity: "C",
    baseAtk: 45,
    baseDef: 40,
    colorido: 2,
    flavorText: "La calle está vacía a esta hora.",
    hint: "Устойчивое: 'en la calle' — на улице.",
    tags: ["básico", "ciudad"],
    quizCorrect: "улица",
    quizOptions: ["улица", "окно", "вода", "книга"],
  },
  {
    language: "es",
    word: "amigo",
    translationRu: "друг",
    type: "Person",
    rarity: "C",
    baseAtk: 50,
    baseDef: 35,
    colorido: 2,
    flavorText: "—Che, ¿venís? —Sí, voy con un amigo.",
    hint: "Форма мн. числа: amigos; женская: amiga.",
    tags: ["básico", "relaciones"],
    quizCorrect: "друг",
    quizOptions: ["друг", "враг", "учитель", "брат"],
  },
  {
    language: "es",
    word: "madre",
    translationRu: "мама",
    type: "Person",
    rarity: "C",
    baseAtk: 45,
    baseDef: 55,
    colorido: 2,
    flavorText: "Mi madre cocina muy rico.",
    hint: "Часто употребляется как 'mi madre' — моя мама.",
    tags: ["familia", "básico"],
    quizCorrect: "мама",
    quizOptions: ["мама", "папа", "сестра", "дочь"],
  },
  {
    language: "es",
    word: "doctor",
    translationRu: "врач",
    type: "Person",
    rarity: "C",
    baseAtk: 55,
    baseDef: 45,
    colorido: 2,
    flavorText: "El doctor me dijo que descanse.",
    hint: "Женская форма: doctora.",
    tags: ["profesión", "salud"],
    quizCorrect: "врач",
    quizOptions: ["врач", "водитель", "повар", "продавец"],
  },
  {
    language: "es",
    word: "comer",
    translationRu: "есть (кушать)",
    type: "Action",
    rarity: "C",
    baseAtk: 55,
    baseDef: 35,
    colorido: 2,
    flavorText: "Vamos a comer algo antes de salir.",
    hint: "Глагол: 'yo como' — я ем.",
    tags: ["básico", "verbo"],
    canEvolve: true,
    quizCorrect: "есть",
    quizOptions: ["есть", "пить", "спать", "бежать"],
    evolutionData: {
      presente: ["como", "comes", "come", "comemos", "comen"],
      participio: "comido",
    },
  },
  {
    language: "es",
    word: "ir",
    translationRu: "идти, ехать",
    type: "Action",
    rarity: "C",
    baseAtk: 50,
    baseDef: 60,
    colorido: 3,
    flavorText: "—¿Vamos al centro? —Dale, vamos.",
    hint: "Неправильный глагол. Presente: voy, vas, va…",
    tags: ["básico", "verbo", "irregular"],
    canEvolve: true,
    quizCorrect: "идти",
    quizOptions: ["идти", "стоять", "прыгать", "читать"],
    evolutionData: {
      presente: ["voy", "vas", "va", "vamos", "van"],
      pretérito: ["fui", "fuiste", "fue", "fuimos", "fueron"],
      participio: "ido",
    },
  },
  {
    language: "es",
    word: "vivir",
    translationRu: "жить",
    type: "Action",
    rarity: "C",
    baseAtk: 45,
    baseDef: 40,
    colorido: 2,
    flavorText: "Quiero vivir cerca del mar algún día.",
    hint: "Глагол 3-й группы (-ir).",
    tags: ["básico", "verbo"],
    canEvolve: true,
    quizCorrect: "жить",
    quizOptions: ["жить", "умирать", "покупать", "плакать"],
    evolutionData: {
      presente: ["vivo", "vives", "vive", "vivimos", "viven"],
      participio: "vivido",
    },
  },
  {
    language: "es",
    word: "libro",
    translationRu: "книга",
    type: "Object",
    rarity: "C",
    baseAtk: 40,
    baseDef: 45,
    colorido: 2,
    flavorText: "Estoy leyendo un libro interesante.",
    hint: "Мн. число: libros.",
    tags: ["básico", "objetos"],
    quizCorrect: "книга",
    quizOptions: ["книга", "стол", "ключ", "яблоко"],
  },
  {
    language: "es",
    word: "mesa",
    translationRu: "стол",
    type: "Object",
    rarity: "C",
    baseAtk: 35,
    baseDef: 50,
    colorido: 2,
    flavorText: "La mesa es de madera y pesa mucho.",
    hint: "Женский род: la mesa.",
    tags: ["básico", "objetos"],
    quizCorrect: "стол",
    quizOptions: ["стол", "стул", "окно", "дорога"],
  },
  {
    language: "es",
    word: "teléfono",
    translationRu: "телефон",
    type: "Object",
    rarity: "C",
    baseAtk: 50,
    baseDef: 40,
    colorido: 3,
    flavorText: "No tengo batería en el teléfono.",
    hint: "Ударение на 'é': teléfono.",
    tags: ["tecnología", "básico"],
    quizCorrect: "телефон",
    quizOptions: ["телефон", "ноутбук", "карандаш", "поезд"],
  },
  {
    language: "es",
    word: "feliz",
    translationRu: "счастливый",
    type: "Emotion",
    rarity: "C",
    baseAtk: 45,
    baseDef: 35,
    colorido: 3,
    flavorText: "Estoy feliz porque hoy es viernes.",
    hint: "С 'estar' — состояние: estoy feliz.",
    tags: ["emociones", "básico"],
    quizCorrect: "счастливый",
    quizOptions: ["счастливый", "злой", "голодный", "холодный"],
  },
  {
    language: "es",
    word: "triste",
    translationRu: "грустный",
    type: "Emotion",
    rarity: "C",
    baseAtk: 35,
    baseDef: 50,
    colorido: 3,
    flavorText: "No estés triste, todo va a salir bien.",
    hint: "Так же с 'estar': estar triste.",
    tags: ["emociones", "básico"],
    quizCorrect: "грустный",
    quizOptions: ["грустный", "весёлый", "быстрый", "высокий"],
  },
  {
    language: "es",
    word: "por favor",
    translationRu: "пожалуйста",
    type: "Expression",
    rarity: "C",
    baseAtk: 60,
    baseDef: 30,
    colorido: 2,
    flavorText: "Un café con leche, por favor.",
    hint: "Вежливая формула просьбы.",
    tags: ["básico", "cortesía"],
    quizCorrect: "пожалуйста",
    quizOptions: ["пожалуйста", "привет", "пока", "спасибо"],
  },

  // UC (8)
  {
    language: "es",
    word: "vecino",
    translationRu: "сосед",
    type: "Person",
    rarity: "UC",
    baseAtk: 55,
    baseDef: 45,
    colorido: 3,
    flavorText: "El vecino siempre saluda cuando me ve.",
    hint: "Женская форма: vecina.",
    tags: ["relaciones", "barrio"],
    quizCorrect: "сосед",
    quizOptions: ["сосед", "друг", "начальник", "врач"],
  },
  {
    language: "es",
    word: "estación",
    translationRu: "станция",
    type: "Place",
    rarity: "UC",
    baseAtk: 50,
    baseDef: 55,
    colorido: 3,
    flavorText: "Nos vemos en la estación a las seis.",
    hint: "Ударение на 'ó': estación.",
    tags: ["transporte", "ciudad"],
    quizCorrect: "станция",
    quizOptions: ["станция", "площадь", "квартира", "гора"],
  },
  {
    language: "es",
    word: "manejar",
    translationRu: "водить (машину)",
    type: "Action",
    rarity: "UC",
    baseAtk: 60,
    baseDef: 50,
    colorido: 3,
    flavorText: "No me gusta manejar de noche con lluvia.",
    hint: "В Лат. Америке чаще 'manejar', в Испании — 'conducir'.",
    tags: ["verbo", "transporte"],
    canEvolve: true,
    quizCorrect: "водить",
    quizOptions: ["водить", "летать", "плавать", "бросать"],
    evolutionData: {
      presente: ["manejo", "manejas", "maneja", "manejamos", "manejan"],
      participio: "manejado",
    },
  },
  {
    language: "es",
    word: "buscar",
    translationRu: "искать",
    type: "Action",
    rarity: "UC",
    baseAtk: 65,
    baseDef: 40,
    colorido: 3,
    flavorText: "Estoy buscando mis llaves. ¿Las viste?",
    hint: "Устойчивое: buscar trabajo — искать работу.",
    tags: ["verbo", "búsqueda"],
    canEvolve: true,
    quizCorrect: "искать",
    quizOptions: ["искать", "терять", "находить", "ждать"],
    evolutionData: {
      presente: ["busco", "buscas", "busca", "buscamos", "buscan"],
      participio: "buscado",
    },
  },
  {
    language: "es",
    word: "llave",
    translationRu: "ключ",
    type: "Object",
    rarity: "UC",
    baseAtk: 50,
    baseDef: 60,
    colorido: 3,
    flavorText: "Se me perdió la llave del departamento.",
    hint: "Женский род: la llave.",
    tags: ["objetos", "hogar"],
    quizCorrect: "ключ",
    quizOptions: ["ключ", "замок", "дверь", "окно"],
  },
  {
    language: "es",
    word: "orgulloso",
    translationRu: "гордый",
    type: "Emotion",
    rarity: "UC",
    baseAtk: 55,
    baseDef: 55,
    colorido: 4,
    flavorText: "Estoy orgulloso de lo que logramos juntos.",
    hint: "Форма жен. рода: orgullosa.",
    tags: ["emociones", "carácter"],
    quizCorrect: "гордый",
    quizOptions: ["гордый", "смущённый", "испуганный", "сонный"],
  },
  {
    language: "es",
    word: "¿Qué tal?",
    translationRu: "как дела?",
    type: "Expression",
    rarity: "UC",
    baseAtk: 70,
    baseDef: 35,
    colorido: 4,
    flavorText: "—¡Hola! ¿Qué tal? —Todo bien, ¿y vos?",
    hint: "Универсальная формула 'как дела?'.",
    tags: ["saludo", "conversación"],
    quizCorrect: "как дела?",
    quizOptions: ["как дела?", "сколько стоит?", "где это?", "который час?"],
  },
  {
    language: "es",
    word: "de nada",
    translationRu: "не за что",
    type: "Expression",
    rarity: "UC",
    baseAtk: 60,
    baseDef: 40,
    colorido: 3,
    flavorText: "—Gracias por la ayuda. —De nada.",
    hint: "Ответ на 'gracias'.",
    tags: ["cortesía", "conversación"],
    quizCorrect: "не за что",
    quizOptions: ["не за что", "спасибо", "извини", "пожалуйста"],
  },

  // R (5)
  {
    language: "es",
    word: "laburar",
    translationRu: "работать (сленг, Аргентина)",
    type: "Action",
    rarity: "R",
    baseAtk: 75,
    baseDef: 50,
    colorido: 8,
    flavorText:
      "—Dale, dejá de boludearte y ponete a laburar. —¿Laburar? ¡Si es domingo!",
    hint: "Лунфардо: от итал. lavorare. Очень типично для Аргентины.",
    tags: ["lunfardo", "informal", "Argentina"],
    canEvolve: true,
    quizCorrect: "работать",
    quizOptions: ["работать", "играть", "спать", "есть"],
    evolutionData: {
      equivalente: "trabajar",
      presente: ["laburo", "laburás", "labura", "laburamos", "laburan"],
    },
  },
  {
    language: "es",
    word: "pibe",
    translationRu: "парень, пацан (Аргентина)",
    type: "Person",
    rarity: "R",
    baseAtk: 65,
    baseDef: 45,
    colorido: 7,
    flavorText: "Ese pibe juega al fútbol como un crack.",
    hint: "Разговорное. В Аргентине: pibe/piba.",
    tags: ["lunfardo", "informal", "Argentina"],
    quizCorrect: "парень",
    quizOptions: ["парень", "девушка", "учитель", "врач"],
  },
  {
    language: "es",
    word: "bondi",
    translationRu: "автобус (сленг, Аргентина)",
    type: "Object",
    rarity: "R",
    baseAtk: 60,
    baseDef: 55,
    colorido: 8,
    flavorText: "Me tomo el bondi a las siete para llegar a tiempo.",
    hint: "В Аргентине 'bondi' = colectivo (автобус).",
    tags: ["transporte", "lunfardo", "Argentina"],
    quizCorrect: "автобус",
    quizOptions: ["автобус", "поезд", "такси", "велосипед"],
  },
  {
    language: "es",
    word: "bajón",
    translationRu: "уныние, «облом» (разг.)",
    type: "Emotion",
    rarity: "R",
    baseAtk: 55,
    baseDef: 70,
    colorido: 7,
    flavorText: "Qué bajón… justo hoy se cortó la luz.",
    hint: "Очень разговорно: 'qué bajón' — ну и облом/печально.",
    tags: ["informal", "emociones"],
    quizCorrect: "уныние",
    quizOptions: ["уныние", "радость", "удивление", "страх"],
  },
  {
    language: "es",
    word: "che",
    translationRu: "эй; слушай (обращение)",
    type: "Expression",
    rarity: "R",
    baseAtk: 70,
    baseDef: 35,
    colorido: 8,
    flavorText: "Che, ¿me pasás la sal?",
    hint: "Типичное обращение в Аргентине/Уругвае.",
    tags: ["Argentina", "conversación", "informal"],
    quizCorrect: "эй",
    quizOptions: ["эй", "спасибо", "пожалуйста", "извини"],
  },

  // SR (2)
  {
    language: "es",
    word: "desvelarse",
    translationRu: "не спать (из-за волнения)",
    type: "Action",
    rarity: "SR",
    baseAtk: 70,
    baseDef: 80,
    colorido: 6,
    flavorText: "Anoche me desvelé pensando en el examen.",
    hint: "Глагол возвратный: desvelarse (лишаться сна).",
    tags: ["verbo", "salud", "emociones"],
    canEvolve: true,
    quizCorrect: "не спать",
    quizOptions: ["не спать", "заснуть", "поесть", "погулять"],
    evolutionData: {
      presente: ["me desvelo", "te desvelás", "se desvela", "nos desvelamos", "se desvelan"],
      participio: "desvelado",
    },
  },
  {
    language: "es",
    word: "estar en las nubes",
    translationRu: "витать в облаках",
    type: "Expression",
    rarity: "SR",
    baseAtk: 80,
    baseDef: 55,
    colorido: 7,
    flavorText: "Perdón, estaba en las nubes y no escuché tu pregunta.",
    hint: "Идиома: быть рассеянным/мечтать.",
    tags: ["idioma", "conversación"],
    quizCorrect: "витать в облаках",
    quizOptions: ["витать в облаках", "быть голодным", "быть усталым", "быть злым"],
  }
];

const main = async (): Promise<void> => {
  const player =
    (await prisma.player.findFirst({ orderBy: { createdAt: "asc" } })) ??
    (await prisma.player.create({ data: { name: "Player", dust: STARTING_DUST } }));

  for (const w of WORDS) {
    await prisma.word.upsert({
      where: { language_word: { language: w.language, word: w.word } },
      create: {
        language: w.language,
        word: w.word,
        translationRu: w.translationRu,
        type: w.type,
        rarity: w.rarity,
        baseAtk: w.baseAtk,
        baseDef: w.baseDef,
        colorido: w.colorido,
        flavorText: w.flavorText,
        hint: w.hint,
        tags: w.tags,
        canEvolve: w.canEvolve ?? false,
        imagePrompt: w.imagePrompt ?? null,
        quizCorrect: w.quizCorrect,
        quizOptions: w.quizOptions,
        evolutionData: w.evolutionData ?? undefined,
      },
      update: {
        translationRu: w.translationRu,
        type: w.type,
        rarity: w.rarity,
        baseAtk: w.baseAtk,
        baseDef: w.baseDef,
        colorido: w.colorido,
        flavorText: w.flavorText,
        hint: w.hint,
        tags: w.tags,
        canEvolve: w.canEvolve ?? false,
        imagePrompt: w.imagePrompt ?? null,
        quizCorrect: w.quizCorrect,
        quizOptions: w.quizOptions,
        evolutionData: w.evolutionData ?? undefined,
      },
    });
  }

  // Migrate existing Spanish IDs to English (idempotent)
  await prisma.word.updateMany({ where: { type: "Persona" }, data: { type: "Person" } });
  await prisma.word.updateMany({ where: { type: "Lugar" }, data: { type: "Place" } });
  await prisma.word.updateMany({ where: { type: "Acción" }, data: { type: "Action" } });
  await prisma.word.updateMany({ where: { type: "Objeto" }, data: { type: "Object" } });
  await prisma.word.updateMany({ where: { type: "Emoción" }, data: { type: "Emotion" } });
  await prisma.word.updateMany({
    where: { type: "Expresión" },
    data: { type: "Expression" },
  });

  await prisma.card.updateMany({
    where: { condition: "Brillante" },
    data: { condition: "Brilliant" },
  });
  await prisma.card.updateMany({ where: { condition: "Gastada" }, data: { condition: "Worn" } });
  await prisma.card.updateMany({
    where: { condition: "Deteriorada" },
    data: { condition: "Deteriorated" },
  });

  const total = await prisma.word.count();
  await prisma.card.updateMany({ where: { playerId: null }, data: { playerId: player.id } });
  // eslint-disable-next-line no-console
  console.log(`Seed complete. Words in pool: ${total}. Player: ${player.id}`);
};

try {
  await main();
} finally {
  await prisma.$disconnect();
}
