/**
 * Theme: kitchen — reference pack.
 * Phase 2.18 Content Foundation, TASK-051.
 *
 * This is the ESTABLISHED STYLE REFERENCE for all subsequent themes.
 * Rules applied here are extracted to docs/content-generation-prompt.md.
 *
 * Style rules (from content-plan.md § 5.6, audit, TASK-051):
 *
 * DIALECT: Rioplatense Spanish.
 *   - voseo in all flavor texts (vos tenés, vos podés, sentate)
 *   - rioplatense vocabulary: heladera (not nevera), manteca (not mantequilla),
 *     palta (not aguacate), facturas, medialuna, dulce de leche, asado, parrilla
 *   - never use Spain/Castilian synonyms
 *
 * HINTS (mnemonics): concrete fonetic/morphologic association that raises the
 * meaning in one mental step. NEVER "sounds soft", NEVER pure description.
 * Allowed patterns:
 *   a) Internationalism: "X ≈ Y in English/Russian"
 *   b) Phonetic link with explanation: "X sounds like Y, which means Z because..."
 *   c) Morphology: "X = prefix + root, together means..."
 *
 * FLAVOR by rarity:
 *   C: 5-10 words, 1 sentence, everyday voseo
 *   UC: 6-12 words, with context/small dialog
 *   R: 8-15 words, argentine slice of life
 *   SR: 10-20 words, cultural context mandatory
 *
 * QUIZ DISTRACTORS:
 *   All three distractors MUST come from the same theme AND preferably same type.
 *   No semantic random junk ("школа" as a distractor for "сковорода").
 *
 * CEFR:
 *   All kitchen C/UC → A1 (except cook_person/specialty foods → A2).
 *   R regional dishes → A2. SR lunfardo idioms → B1.
 *
 * COLORIDO:
 *   C: 1-2 | UC: 2-4 | R: 4-6 | SR: 6-8 | SSR: 7-10
 *
 * STATS (baseAtk / baseDef):
 *   Object (foods): ATK 30-60, DEF 40-70 (defensive)
 *   Object (tools): ATK 45-65, DEF 40-60
 *   Action (cook verbs): ATK 55-75, DEF 35-55 (aggressive)
 *   Emotion (taste): ATK 40-60, DEF 45-65
 *   Person: ATK 50-70, DEF 45-65
 *   Expression: ATK 55-75, DEF 40-60
 *
 * THEMATIC dispersion inside the theme:
 *   ~50% C, ~25% UC, ~15% R, ~8% SR, ~2% SSR
 */

import type { SeedWord } from "./seed-words.types.js";

export const KITCHEN_WORDS: SeedWord[] = [
  // ==========================================================================
  // PLACES — кухонное пространство (5)
  // ==========================================================================
  {
    language: "es",
    conceptKey: "kitchen",
    word: "cocina",
    translationRu: "кухня",
    type: "Place",
    rarity: "C",
    baseAtk: 40,
    baseDef: 60,
    colorido: 1,
    flavorText: "Vení a la cocina, ya está el café listo.",
    hint: "«Cocina» — прямой родственник английского «cook» (cook + место): место, где готовят.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen", "home"],
    quizCorrect: "кухня",
    quizOptions: ["кухня", "столовая", "кладовая", "духовка"],
  },
  {
    language: "es",
    conceptKey: "fridge",
    word: "heladera",
    translationRu: "холодильник",
    type: "Object",
    rarity: "C",
    baseAtk: 35,
    baseDef: 65,
    colorido: 3,
    flavorText: "Hay un tupper con milanesas en la heladera.",
    hint: "«Heladera» от «helado» (мороженое) + суффикс «-era» (вместилище): где лежит холодное. Аргентинизм — в Испании «nevera».",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen", "home"],
    quizCorrect: "холодильник",
    quizOptions: ["холодильник", "духовка", "микроволновка", "плита"],
  },
  {
    language: "es",
    conceptKey: "oven",
    word: "horno",
    translationRu: "духовка",
    type: "Object",
    rarity: "C",
    baseAtk: 55,
    baseDef: 50,
    colorido: 1,
    flavorText: "Metelo al horno veinte minutos y listo.",
    hint: "«Horno» родственник «hornero» (печник): печь, духовка. Корень как в английском «furnace».",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen"],
    quizCorrect: "духовка",
    quizOptions: ["духовка", "холодильник", "сковорода", "кастрюля"],
  },
  {
    language: "es",
    conceptKey: "microwave",
    word: "microondas",
    translationRu: "микроволновка",
    type: "Object",
    rarity: "C",
    baseAtk: 45,
    baseDef: 55,
    colorido: 1,
    flavorText: "Calentalo treinta segundos en el microondas.",
    hint: "«Microondas» = micro (микро) + ondas (волны) — дословно «микроволны»: это и есть микроволновка.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen"],
    quizCorrect: "микроволновка",
    quizOptions: ["микроволновка", "духовка", "холодильник", "сковорода"],
  },
  {
    language: "es",
    conceptKey: "pantry",
    word: "alacena",
    translationRu: "кладовая / шкаф для продуктов",
    type: "Place",
    rarity: "UC",
    baseAtk: 35,
    baseDef: 70,
    colorido: 2,
    flavorText: "Fijate en la alacena, ahí hay yerba.",
    hint: "«Alacena» — от арабского al-ḫazana (хранилище). Место хранения запасов = кладовая.",
    tags: [],
    cefrLevel: "A2",
    themes: ["kitchen", "home"],
    quizCorrect: "кладовая / шкаф для продуктов",
    quizOptions: [
      "кладовая / шкаф для продуктов",
      "холодильник",
      "духовка",
      "кухонный стол",
    ],
  },

  // ==========================================================================
  // ACTIONS — готовка (18)
  // ==========================================================================
  {
    language: "es",
    conceptKey: "cook_action",
    word: "cocinar",
    translationRu: "готовить (еду)",
    type: "Action",
    rarity: "C",
    baseAtk: 65,
    baseDef: 40,
    colorido: 2,
    flavorText: "Hoy cocino yo, vos ponés la mesa.",
    hint: "«Cocinar» — корень тот же что в «cocina» и английском «cook»: готовить еду.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen"],
    quizCorrect: "готовить (еду)",
    quizOptions: ["готовить (еду)", "жарить", "варить", "резать"],
  },
  {
    language: "es",
    conceptKey: "eat",
    word: "comer",
    translationRu: "есть (кушать)",
    type: "Action",
    rarity: "C",
    baseAtk: 65,
    baseDef: 35,
    colorido: 2,
    flavorText: "¿Ya comiste? Dejé milanesas en la mesada.",
    hint: "«Comer» — тот же корень что в русском «комок» (еды) и «consume»: класть в рот, есть.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen", "eating-out"],
    quizCorrect: "есть (кушать)",
    quizOptions: ["есть (кушать)", "пить", "жевать", "глотать"],
  },
  {
    language: "es",
    conceptKey: "drink",
    word: "beber",
    translationRu: "пить",
    type: "Action",
    rarity: "C",
    baseAtk: 55,
    baseDef: 40,
    colorido: 1,
    flavorText: "Prefiero beber agua fresca, no tan helada.",
    hint: "«Beber» — от латинского bibere, тот же корень что в «beverage» (напиток) в английском: пить.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen", "eating-out"],
    quizCorrect: "пить",
    quizOptions: ["пить", "есть (кушать)", "глотать", "пробовать"],
  },
  {
    language: "es",
    conceptKey: "take_drink",
    word: "tomar",
    translationRu: "пить (арг.) / брать",
    type: "Action",
    rarity: "C",
    baseAtk: 60,
    baseDef: 45,
    colorido: 3,
    flavorText: "Tomamos mate todas las mañanas, es un ritual.",
    hint: "«Tomar» — родственник английского «take»: брать. В Аргентине «tomar algo» = пить, «брать» жидкость в себя.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen", "eating-out"],
    quizCorrect: "пить (арг.) / брать",
    quizOptions: ["пить (арг.) / брать", "есть (кушать)", "жевать", "наливать"],
  },
  {
    language: "es",
    conceptKey: "boil",
    word: "hervir",
    translationRu: "варить / кипятить",
    type: "Action",
    rarity: "UC",
    baseAtk: 65,
    baseDef: 45,
    colorido: 2,
    flavorText: "Poné el agua a hervir mientras corto la cebolla.",
    hint: "«Hervir» — корень тот же что в «effervescence» (бурление): кипение, варить.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen"],
    quizCorrect: "варить / кипятить",
    quizOptions: ["варить / кипятить", "жарить", "запекать", "резать"],
  },
  {
    language: "es",
    conceptKey: "fry",
    word: "freír",
    translationRu: "жарить (на масле)",
    type: "Action",
    rarity: "UC",
    baseAtk: 70,
    baseDef: 40,
    colorido: 2,
    flavorText: "Freí las milanesas de los dos lados, dos minutos cada uno.",
    hint: "«Freír» родственник английского «fry» и русского «фритюр»: жарить в масле.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen"],
    quizCorrect: "жарить (на масле)",
    quizOptions: ["жарить (на масле)", "варить", "запекать", "тушить"],
  },
  {
    language: "es",
    conceptKey: "bake",
    word: "hornear",
    translationRu: "запекать / печь",
    type: "Action",
    rarity: "UC",
    baseAtk: 60,
    baseDef: 45,
    colorido: 2,
    flavorText: "Horneá a 180 grados hasta que se dore.",
    hint: "«Hornear» — буквально «использовать horno (духовку)»: запекать, печь в духовке.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen"],
    quizCorrect: "запекать / печь",
    quizOptions: ["запекать / печь", "жарить (на масле)", "варить", "жарить на углях"],
  },
  {
    language: "es",
    conceptKey: "grill_asado",
    word: "asar",
    translationRu: "жарить на углях / запекать",
    type: "Action",
    rarity: "UC",
    baseAtk: 70,
    baseDef: 45,
    colorido: 5,
    flavorText: "El domingo asamos tira de asado con los pibes.",
    hint: "«Asar» — тот же корень что в «asado» (аргентинское барбекю). Жарить на углях, на открытом огне.",
    tags: [],
    cefrLevel: "A2",
    themes: ["kitchen"],
    quizCorrect: "жарить на углях / запекать",
    quizOptions: [
      "жарить на углях / запекать",
      "жарить (на масле)",
      "варить",
      "запекать в духовке",
    ],
  },
  {
    language: "es",
    conceptKey: "cut",
    word: "cortar",
    translationRu: "резать",
    type: "Action",
    rarity: "C",
    baseAtk: 65,
    baseDef: 40,
    colorido: 1,
    flavorText: "Cortá la cebolla en cubitos chiquitos.",
    hint: "«Cortar» — тот же корень что в «короткий» и в английском «cut short»: делать короче, резать.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen"],
    quizCorrect: "резать",
    quizOptions: ["резать", "чистить", "мешать", "варить"],
  },
  {
    language: "es",
    conceptKey: "peel",
    word: "pelar",
    translationRu: "чистить (кожуру)",
    type: "Action",
    rarity: "UC",
    baseAtk: 55,
    baseDef: 45,
    colorido: 2,
    flavorText: "Pelá las papas antes de hervirlas.",
    hint: "«Pelar» — корень «piel» (кожа): снимать кожу, чистить кожуру.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen"],
    quizCorrect: "чистить (кожуру)",
    quizOptions: ["чистить (кожуру)", "резать", "тереть", "нарезать кубиками"],
  },
  {
    language: "es",
    conceptKey: "chop",
    word: "picar",
    translationRu: "измельчать / нарезать мелко",
    type: "Action",
    rarity: "UC",
    baseAtk: 60,
    baseDef: 40,
    colorido: 2,
    flavorText: "Picá el ajo bien finito antes de ponerlo.",
    hint: "«Picar» — буквально «клевать/колоть», то же как по-русски «искрошить»: мелко нарезать.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen"],
    quizCorrect: "измельчать / нарезать мелко",
    quizOptions: [
      "измельчать / нарезать мелко",
      "чистить (кожуру)",
      "резать (крупно)",
      "перемешивать",
    ],
  },
  {
    language: "es",
    conceptKey: "mix",
    word: "mezclar",
    translationRu: "смешивать",
    type: "Action",
    rarity: "UC",
    baseAtk: 55,
    baseDef: 45,
    colorido: 1,
    flavorText: "Mezclá todo bien hasta que quede homogéneo.",
    hint: "«Mezclar» — прямой родственник английского «mix»: смешивать.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen"],
    quizCorrect: "смешивать",
    quizOptions: ["смешивать", "перемешивать (ложкой)", "резать", "пробовать"],
  },
  {
    language: "es",
    conceptKey: "stir",
    word: "revolver",
    translationRu: "перемешивать (ложкой)",
    type: "Action",
    rarity: "UC",
    baseAtk: 50,
    baseDef: 45,
    colorido: 2,
    flavorText: "Revolvé de vez en cuando para que no se pegue.",
    hint: "«Revolver» — тот же корень что в «revolution»: вращать. Перемешивать круговыми движениями.",
    tags: [],
    cefrLevel: "A2",
    themes: ["kitchen"],
    quizCorrect: "перемешивать (ложкой)",
    quizOptions: ["перемешивать (ложкой)", "смешивать", "взбивать", "резать"],
  },
  {
    language: "es",
    conceptKey: "taste",
    word: "probar",
    translationRu: "пробовать (на вкус)",
    type: "Action",
    rarity: "C",
    baseAtk: 55,
    baseDef: 50,
    colorido: 2,
    flavorText: "Probá la sopa a ver si le falta sal.",
    hint: "«Probar» — тот же корень что в «проба» (пробовать): тестировать на вкус.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen", "eating-out"],
    quizCorrect: "пробовать (на вкус)",
    quizOptions: ["пробовать (на вкус)", "есть (кушать)", "пить", "нюхать"],
  },
  {
    language: "es",
    conceptKey: "serve",
    word: "servir",
    translationRu: "подавать (еду) / наливать",
    type: "Action",
    rarity: "C",
    baseAtk: 60,
    baseDef: 45,
    colorido: 2,
    flavorText: "Te sirvo un poco más de vino, dale.",
    hint: "«Servir» — тот же корень что «service»: обслуживать, подавать за столом.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen", "eating-out"],
    quizCorrect: "подавать (еду) / наливать",
    quizOptions: ["подавать (еду) / наливать", "пробовать", "есть (кушать)", "готовить (еду)"],
  },
  {
    language: "es",
    conceptKey: "heat_up",
    word: "calentar",
    translationRu: "подогревать / разогревать",
    type: "Action",
    rarity: "C",
    baseAtk: 55,
    baseDef: 50,
    colorido: 1,
    flavorText: "Calentá el guiso de ayer, está mejor al otro día.",
    hint: "«Calentar» — тот же корень что «caliente» (горячий): делать горячим, подогревать.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen"],
    quizCorrect: "подогревать / разогревать",
    quizOptions: ["подогревать / разогревать", "охлаждать", "замораживать", "готовить (еду)"],
  },
  {
    language: "es",
    conceptKey: "chew",
    word: "masticar",
    translationRu: "жевать",
    type: "Action",
    rarity: "UC",
    baseAtk: 50,
    baseDef: 50,
    colorido: 2,
    flavorText: "Masticá bien antes de tragar, nene.",
    hint: "«Masticar» — родственник английского «masticate» и русского «мастика» (что жуётся): жевать.",
    tags: [],
    cefrLevel: "A2",
    themes: ["kitchen", "eating-out"],
    quizCorrect: "жевать",
    quizOptions: ["жевать", "глотать", "есть (кушать)", "откусывать"],
  },
  {
    language: "es",
    conceptKey: "swallow",
    word: "tragar",
    translationRu: "глотать",
    type: "Action",
    rarity: "UC",
    baseAtk: 55,
    baseDef: 45,
    colorido: 2,
    flavorText: "Tomate un vaso de agua para tragar la pastilla.",
    hint: "«Tragar» звучит как «трагедия» — которую тяжело «проглотить»: глотать, проглатывать.",
    tags: [],
    cefrLevel: "A2",
    themes: ["kitchen", "body-health"],
    quizCorrect: "глотать",
    quizOptions: ["глотать", "жевать", "пить", "есть (кушать)"],
  },
  {
    language: "es",
    conceptKey: "knead",
    word: "amasar",
    translationRu: "месить (тесто)",
    type: "Action",
    rarity: "R",
    baseAtk: 55,
    baseDef: 55,
    colorido: 3,
    flavorText: "Mi abuela amasa las pastas los domingos, como siempre.",
    hint: "«Amasar» — корень «masa» (масса/тесто): делать massa, месить.",
    tags: [],
    cefrLevel: "A2",
    themes: ["kitchen"],
    quizCorrect: "месить (тесто)",
    quizOptions: ["месить (тесто)", "смешивать", "перемешивать (ложкой)", "взбивать"],
  },

  // ==========================================================================
  // OBJECTS — посуда и приборы (15)
  // ==========================================================================
  {
    language: "es",
    conceptKey: "plate",
    word: "plato",
    translationRu: "тарелка",
    type: "Object",
    rarity: "C",
    baseAtk: 35,
    baseDef: 60,
    colorido: 1,
    flavorText: "Pasame un plato hondo para la sopa.",
    hint: "«Plato» — прямой родственник английского «plate»: тарелка.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen", "eating-out"],
    quizCorrect: "тарелка",
    quizOptions: ["тарелка", "чашка", "стакан", "миска"],
  },
  {
    language: "es",
    conceptKey: "glass_drink",
    word: "vaso",
    translationRu: "стакан",
    type: "Object",
    rarity: "C",
    baseAtk: 35,
    baseDef: 55,
    colorido: 1,
    flavorText: "Me das un vaso de agua, por favor?",
    hint: "«Vaso» — тот же корень что в «vase» (ваза) и «vessel» (сосуд): сосуд для питья, стакан.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen", "eating-out"],
    quizCorrect: "стакан",
    quizOptions: ["стакан", "чашка", "тарелка", "бокал"],
  },
  {
    language: "es",
    conceptKey: "cup",
    word: "taza",
    translationRu: "чашка",
    type: "Object",
    rarity: "C",
    baseAtk: 35,
    baseDef: 55,
    colorido: 2,
    flavorText: "¿Querés una taza de té con leche?",
    hint: "«Taza» по звучанию почти «таз» (только маленький) — посуда, из которой пьют: чашка.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen", "morning-routine"],
    quizCorrect: "чашка",
    quizOptions: ["чашка", "стакан", "тарелка", "бокал"],
  },
  {
    language: "es",
    conceptKey: "spoon",
    word: "cuchara",
    translationRu: "ложка",
    type: "Object",
    rarity: "C",
    baseAtk: 40,
    baseDef: 50,
    colorido: 1,
    flavorText: "Necesito una cuchara para el yogur.",
    hint: "«Cuchara» — корень тот же что в «кухня/cuchen»: кухонный столовый прибор. Ложка.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen", "eating-out"],
    quizCorrect: "ложка",
    quizOptions: ["ложка", "вилка", "нож", "чайная ложка"],
  },
  {
    language: "es",
    conceptKey: "fork",
    word: "tenedor",
    translationRu: "вилка",
    type: "Object",
    rarity: "C",
    baseAtk: 45,
    baseDef: 45,
    colorido: 1,
    flavorText: "Falta un tenedor en la mesa, traé uno.",
    hint: "«Tenedor» от «tener» (держать, иметь) + «-dor» (инструмент): инструмент для того, чтобы держать еду = вилка.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen", "eating-out"],
    quizCorrect: "вилка",
    quizOptions: ["вилка", "ложка", "нож", "зубочистка"],
  },
  {
    language: "es",
    conceptKey: "knife",
    word: "cuchillo",
    translationRu: "нож",
    type: "Object",
    rarity: "C",
    baseAtk: 55,
    baseDef: 40,
    colorido: 2,
    flavorText: "¿Dónde está el cuchillo bueno para el asado?",
    hint: "«Cuchillo» — общий корень с «кухня/cuchen»: кухонный инструмент, который режет. Нож.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen", "eating-out"],
    quizCorrect: "нож",
    quizOptions: ["нож", "вилка", "ложка", "зубочистка"],
  },
  {
    language: "es",
    conceptKey: "pan_fry",
    word: "sartén",
    translationRu: "сковорода",
    type: "Object",
    rarity: "C",
    baseAtk: 50,
    baseDef: 55,
    colorido: 2,
    flavorText: "Calentá la sartén antes de poner el aceite.",
    hint: "«Sartén» — от латинского sartago: плоская посуда для жарки. Сковорода.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen"],
    quizCorrect: "сковорода",
    quizOptions: ["сковорода", "кастрюля", "противень", "миска"],
  },
  {
    language: "es",
    conceptKey: "pot",
    word: "olla",
    translationRu: "кастрюля",
    type: "Object",
    rarity: "C",
    baseAtk: 45,
    baseDef: 60,
    colorido: 2,
    flavorText: "Poné los fideos en la olla grande.",
    hint: "«Olla» похожа на русское «ёлка» по форме — но смотри в латинский корень: aulla — горшок. Кастрюля, большой горшок.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen"],
    quizCorrect: "кастрюля",
    quizOptions: ["кастрюля", "сковорода", "миска", "противень"],
  },
  {
    language: "es",
    conceptKey: "bowl",
    word: "bol",
    translationRu: "миска",
    type: "Object",
    rarity: "UC",
    baseAtk: 35,
    baseDef: 55,
    colorido: 2,
    flavorText: "Batí los huevos en un bol aparte.",
    hint: "«Bol» — прямое заимствование из английского «bowl»: миска.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen"],
    quizCorrect: "миска",
    quizOptions: ["миска", "тарелка", "кастрюля", "чашка"],
  },
  {
    language: "es",
    conceptKey: "mate_gourd",
    word: "mate",
    translationRu: "мате (сосуд и напиток)",
    type: "Object",
    rarity: "R",
    baseAtk: 55,
    baseDef: 55,
    colorido: 7,
    flavorText: "¿Cebás mate? Traje yerba nueva, está rica.",
    hint: "«Mate» — индейское слово (quechua), означает и тыкву-сосуд, и напиток из yerba mate. Культурный символ Аргентины.",
    tags: [],
    cefrLevel: "A2",
    themes: ["kitchen"],
    quizCorrect: "мате (сосуд и напиток)",
    quizOptions: [
      "мате (сосуд и напиток)",
      "чашка",
      "кофе",
      "термос",
    ],
  },
  {
    language: "es",
    conceptKey: "kettle_pava",
    word: "pava",
    translationRu: "чайник (для мате)",
    type: "Object",
    rarity: "UC",
    baseAtk: 40,
    baseDef: 55,
    colorido: 5,
    flavorText: "La pava ya está, cebá unos mates mientras.",
    hint: "«Pava» — в Аргентине это чайник для мате (буквально «индюшка», форма похожа). Специфически rioplatense.",
    tags: [],
    cefrLevel: "A2",
    themes: ["kitchen"],
    quizCorrect: "чайник (для мате)",
    quizOptions: ["чайник (для мате)", "кастрюля", "термос", "мате (сосуд и напиток)"],
  },
  {
    language: "es",
    conceptKey: "napkin",
    word: "servilleta",
    translationRu: "салфетка",
    type: "Object",
    rarity: "C",
    baseAtk: 30,
    baseDef: 50,
    colorido: 1,
    flavorText: "Pasame una servilleta, me ensucié la camisa.",
    hint: "«Servilleta» — корень «servir» (подавать): то, что подают к столу для вытирания. Салфетка.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen", "eating-out"],
    quizCorrect: "салфетка",
    quizOptions: ["салфетка", "скатерть", "полотенце", "фартук"],
  },
  {
    language: "es",
    conceptKey: "tablecloth",
    word: "mantel",
    translationRu: "скатерть",
    type: "Object",
    rarity: "UC",
    baseAtk: 30,
    baseDef: 55,
    colorido: 2,
    flavorText: "Poné el mantel bueno, vienen invitados.",
    hint: "«Mantel» — родственник «manta» (покрывало): то, что покрывает стол = скатерть.",
    tags: [],
    cefrLevel: "A2",
    themes: ["kitchen", "eating-out"],
    quizCorrect: "скатерть",
    quizOptions: ["скатерть", "салфетка", "полотенце", "простыня"],
  },
  {
    language: "es",
    conceptKey: "cutting_board",
    word: "tabla",
    translationRu: "доска (разделочная)",
    type: "Object",
    rarity: "UC",
    baseAtk: 35,
    baseDef: 55,
    colorido: 2,
    flavorText: "Cortá las verduras en la tabla de madera.",
    hint: "«Tabla» — прямой родственник русского «табло» и английского «table»: плоская доска. В кухне — разделочная.",
    tags: [],
    cefrLevel: "A2",
    themes: ["kitchen"],
    quizCorrect: "доска (разделочная)",
    quizOptions: ["доска (разделочная)", "стол", "скатерть", "тарелка"],
  },
  {
    language: "es",
    conceptKey: "strainer",
    word: "colador",
    translationRu: "дуршлаг / сито",
    type: "Object",
    rarity: "UC",
    baseAtk: 35,
    baseDef: 55,
    colorido: 2,
    flavorText: "Escurrí los fideos con el colador grande.",
    hint: "«Colador» — корень «colar» (цедить): инструмент для цеживания. Дуршлаг или сито.",
    tags: [],
    cefrLevel: "A2",
    themes: ["kitchen"],
    quizCorrect: "дуршлаг / сито",
    quizOptions: ["дуршлаг / сито", "миска", "ложка", "сковорода"],
  },

  // ==========================================================================
  // OBJECTS — базовые продукты (22)
  // ==========================================================================
  {
    language: "es",
    conceptKey: "bread",
    word: "pan",
    translationRu: "хлеб",
    type: "Object",
    rarity: "C",
    baseAtk: 35,
    baseDef: 60,
    colorido: 2,
    flavorText: "Compré pan fresquito para el desayuno.",
    hint: "«Pan» — общий корень с итальянским «pane» и латинским panis: хлеб. Максимально базовое слово.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen", "eating-out"],
    quizCorrect: "хлеб",
    quizOptions: ["хлеб", "молоко", "масло", "сахар"],
  },
  {
    language: "es",
    conceptKey: "milk",
    word: "leche",
    translationRu: "молоко",
    type: "Object",
    rarity: "C",
    baseAtk: 30,
    baseDef: 65,
    colorido: 1,
    flavorText: "Tomate la leche tibia antes de dormir.",
    hint: "«Leche» — от латинского lac (родственник английского «lactose»): молочные продукты. Молоко.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen", "morning-routine"],
    quizCorrect: "молоко",
    quizOptions: ["молоко", "йогурт", "сливки", "вода"],
  },
  {
    language: "es",
    conceptKey: "egg",
    word: "huevo",
    translationRu: "яйцо",
    type: "Object",
    rarity: "C",
    baseAtk: 40,
    baseDef: 55,
    colorido: 2,
    flavorText: "¿Me hacés unos huevos revueltos?",
    hint: "«Huevo» — от латинского ovum (отсюда же «ovulum» в биологии): яйцо.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen"],
    quizCorrect: "яйцо",
    quizOptions: ["яйцо", "молоко", "масло", "сыр"],
  },
  {
    language: "es",
    conceptKey: "cheese",
    word: "queso",
    translationRu: "сыр",
    type: "Object",
    rarity: "C",
    baseAtk: 40,
    baseDef: 55,
    colorido: 2,
    flavorText: "Pidamos una tabla de quesos y jamón crudo.",
    hint: "«Queso» — общий корень с английским «cheese» и немецким «Käse», все от латинского caseus: сыр.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen", "eating-out"],
    quizCorrect: "сыр",
    quizOptions: ["сыр", "масло (сливочное)", "йогурт", "молоко"],
  },
  {
    language: "es",
    conceptKey: "butter_manteca",
    word: "manteca",
    translationRu: "сливочное масло",
    type: "Object",
    rarity: "C",
    baseAtk: 40,
    baseDef: 55,
    colorido: 3,
    flavorText: "Untá la tostada con manteca y dulce de leche.",
    hint: "«Manteca» в Rioplatense = сливочное масло. В Испании это «mantequilla» — разные регионы, разные слова.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen", "morning-routine"],
    quizCorrect: "сливочное масло",
    quizOptions: ["сливочное масло", "растительное масло", "сыр", "молоко"],
  },
  {
    language: "es",
    conceptKey: "oil",
    word: "aceite",
    translationRu: "растительное масло",
    type: "Object",
    rarity: "C",
    baseAtk: 45,
    baseDef: 55,
    colorido: 2,
    flavorText: "Un chorrito de aceite de oliva arriba de la ensalada.",
    hint: "«Aceite» — от арабского «az-zayt» (оливковое масло): растительное масло.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen"],
    quizCorrect: "растительное масло",
    quizOptions: ["растительное масло", "сливочное масло", "уксус", "соус"],
  },
  {
    language: "es",
    conceptKey: "salt",
    word: "sal",
    translationRu: "соль",
    type: "Object",
    rarity: "C",
    baseAtk: 45,
    baseDef: 50,
    colorido: 1,
    flavorText: "Pasame la sal, le falta un toque.",
    hint: "«Sal» — прямой родственник русского «соль» и английского «salt»: максимально интернациональное слово.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen"],
    quizCorrect: "соль",
    quizOptions: ["соль", "сахар", "перец", "специи"],
  },
  {
    language: "es",
    conceptKey: "sugar",
    word: "azúcar",
    translationRu: "сахар",
    type: "Object",
    rarity: "C",
    baseAtk: 40,
    baseDef: 50,
    colorido: 2,
    flavorText: "Le pongo dos de azúcar al café, lo quiero dulce.",
    hint: "«Azúcar» — от арабского «as-sukkar» (sugar), отсюда же русское «сахар» и английское «sugar». Интернациональный корень.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen", "morning-routine"],
    quizCorrect: "сахар",
    quizOptions: ["сахар", "соль", "мёд", "сироп"],
  },
  {
    language: "es",
    conceptKey: "pepper_spice",
    word: "pimienta",
    translationRu: "перец (специя)",
    type: "Object",
    rarity: "UC",
    baseAtk: 50,
    baseDef: 45,
    colorido: 3,
    flavorText: "Sal, pimienta y un poco de orégano, nada más.",
    hint: "«Pimienta» — родственник английского «pepper» через латинский piper: перец-специя.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen"],
    quizCorrect: "перец (специя)",
    quizOptions: ["перец (специя)", "соль", "специи", "паприка"],
  },
  {
    language: "es",
    conceptKey: "flour",
    word: "harina",
    translationRu: "мука",
    type: "Object",
    rarity: "C",
    baseAtk: 35,
    baseDef: 55,
    colorido: 2,
    flavorText: "Tamizá la harina antes de ponerla en la masa.",
    hint: "«Harina» — от латинского farina (отсюда «farine» в кулинарии): размолотое зерно. Мука.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen"],
    quizCorrect: "мука",
    quizOptions: ["мука", "сахар", "дрожжи", "крахмал"],
  },
  {
    language: "es",
    conceptKey: "rice",
    word: "arroz",
    translationRu: "рис",
    type: "Object",
    rarity: "C",
    baseAtk: 35,
    baseDef: 55,
    colorido: 2,
    flavorText: "Hacé arroz blanco para acompañar el pollo.",
    hint: "«Arroz» — общий корень с английским «rice» через арабский «ar-ruzz»: рис.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen"],
    quizCorrect: "рис",
    quizOptions: ["рис", "макароны", "картошка", "хлеб"],
  },
  {
    language: "es",
    conceptKey: "pasta",
    word: "fideos",
    translationRu: "макароны / лапша",
    type: "Object",
    rarity: "C",
    baseAtk: 40,
    baseDef: 55,
    colorido: 3,
    flavorText: "Los domingos comemos fideos con tuco, tradición familiar.",
    hint: "«Fideos» — тонкие верёвочки теста, в Аргентине это и макароны, и спагетти. Корень латинский fidejar (делать тонкие нити).",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen", "eating-out"],
    quizCorrect: "макароны / лапша",
    quizOptions: ["макароны / лапша", "рис", "хлеб", "каша"],
  },
  {
    language: "es",
    conceptKey: "chicken",
    word: "pollo",
    translationRu: "курица",
    type: "Object",
    rarity: "C",
    baseAtk: 45,
    baseDef: 55,
    colorido: 2,
    flavorText: "El pollo al horno con papas es infaltable.",
    hint: "«Pollo» родственник английского «poultry» (птицеводство): домашняя птица, курица. Оба от латинского pullus.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen", "pets-animals"],
    quizCorrect: "курица",
    quizOptions: ["курица", "говядина", "свинина", "рыба"],
  },
  {
    language: "es",
    conceptKey: "meat",
    word: "carne",
    translationRu: "мясо (говядина)",
    type: "Object",
    rarity: "C",
    baseAtk: 55,
    baseDef: 55,
    colorido: 4,
    flavorText: "En Argentina la carne es sagrada, el asado también.",
    hint: "«Carne» — тот же корень что в «carnaval» (празднование мяса перед постом): мясо, обычно говядина.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen"],
    quizCorrect: "мясо (говядина)",
    quizOptions: ["мясо (говядина)", "курица", "свинина", "рыба"],
  },
  {
    language: "es",
    conceptKey: "apple",
    word: "manzana",
    translationRu: "яблоко",
    type: "Object",
    rarity: "C",
    baseAtk: 35,
    baseDef: 55,
    colorido: 1,
    flavorText: "Una manzana por día y al médico ni te acercás.",
    hint: "«Manzana» — от латинского mala Matiana (фрукт Matius). Также по-испански означает городской квартал — тот же корень через форму.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen"],
    quizCorrect: "яблоко",
    quizOptions: ["яблоко", "груша", "банан", "апельсин"],
  },
  {
    language: "es",
    conceptKey: "tomato",
    word: "tomate",
    translationRu: "помидор",
    type: "Object",
    rarity: "C",
    baseAtk: 35,
    baseDef: 55,
    colorido: 2,
    flavorText: "Ensalada de tomate, lechuga y cebolla, clásico argentino.",
    hint: "«Tomate» — это то же слово что и русское «томат», из науатль (язык ацтеков) «tomatl».",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen"],
    quizCorrect: "помидор",
    quizOptions: ["помидор", "огурец", "перец", "морковь"],
  },
  {
    language: "es",
    conceptKey: "potato_papa",
    word: "papa",
    translationRu: "картошка",
    type: "Object",
    rarity: "C",
    baseAtk: 35,
    baseDef: 55,
    colorido: 3,
    flavorText: "Hacé papas fritas bien crocantes, por favor.",
    hint: "«Papa» в Латинской Америке = картошка (от quechua «papa»). В Испании — «patata». Не путать с «Papa» (папа римский, мужской род).",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen"],
    quizCorrect: "картошка",
    quizOptions: ["картошка", "батат", "помидор", "морковь"],
  },
  {
    language: "es",
    conceptKey: "onion",
    word: "cebolla",
    translationRu: "лук",
    type: "Object",
    rarity: "C",
    baseAtk: 40,
    baseDef: 50,
    colorido: 2,
    flavorText: "Cortar cebolla sin llorar es un arte.",
    hint: "«Cebolla» — общий корень с английским «scallion» (зелёный лук): луковичные. Лук.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen"],
    quizCorrect: "лук",
    quizOptions: ["лук", "чеснок", "картошка", "помидор"],
  },
  {
    language: "es",
    conceptKey: "garlic",
    word: "ajo",
    translationRu: "чеснок",
    type: "Object",
    rarity: "C",
    baseAtk: 50,
    baseDef: 45,
    colorido: 2,
    flavorText: "Un diente de ajo picado bien finito.",
    hint: "«Ajo» — короткое слово от латинского allium: чеснок. Произносится «ахо» — острое.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen"],
    quizCorrect: "чеснок",
    quizOptions: ["чеснок", "лук", "специи", "перец (специя)"],
  },
  {
    language: "es",
    conceptKey: "avocado_palta",
    word: "palta",
    translationRu: "авокадо",
    type: "Object",
    rarity: "C",
    baseAtk: 35,
    baseDef: 60,
    colorido: 4,
    flavorText: "Tostada con palta y huevo, el desayuno de moda.",
    hint: "«Palta» в Rioplatense = авокадо (от quechua «pallta»). В Мексике и Испании — «aguacate». Региональное различие.",
    tags: [],
    cefrLevel: "A2",
    themes: ["kitchen"],
    quizCorrect: "авокадо",
    quizOptions: ["авокадо", "помидор", "оливка", "лимон"],
  },
  {
    language: "es",
    conceptKey: "yerba_mate",
    word: "yerba",
    translationRu: "йерба (для мате)",
    type: "Object",
    rarity: "R",
    baseAtk: 40,
    baseDef: 60,
    colorido: 7,
    flavorText: "Compré yerba Rosamonte, la que le gusta al viejo.",
    hint: "«Yerba» буквально «трава» (от hierba), но в Rioplatense almost always означает yerba mate — основа национального напитка.",
    tags: [],
    cefrLevel: "A2",
    themes: ["kitchen"],
    quizCorrect: "йерба (для мате)",
    quizOptions: ["йерба (для мате)", "чай", "кофе", "сахар"],
  },

  // ==========================================================================
  // OBJECTS — аргентинские специалитеты (8)
  // ==========================================================================
  {
    language: "es",
    conceptKey: "asado",
    word: "asado",
    translationRu: "асадо (арг. барбекю)",
    type: "Object",
    rarity: "R",
    baseAtk: 60,
    baseDef: 60,
    colorido: 8,
    flavorText: "El asado del domingo es sagrado, no se falta.",
    hint: "«Asado» от «asar» (жарить на углях): главное блюдо и социальный ритуал Аргентины — мясо на parrilla.",
    tags: [],
    cefrLevel: "A2",
    themes: ["kitchen"],
    quizCorrect: "асадо (арг. барбекю)",
    quizOptions: ["асадо (арг. барбекю)", "гриль", "шашлык", "барбекю (нейтр.)"],
  },
  {
    language: "es",
    conceptKey: "grill_parrilla",
    word: "parrilla",
    translationRu: "парилья (гриль)",
    type: "Object",
    rarity: "R",
    baseAtk: 55,
    baseDef: 60,
    colorido: 7,
    flavorText: "Prendé la parrilla temprano, así están las brasas listas.",
    hint: "«Parrilla» — уменьшительное от «parra» (решётка из лозы): решётка для асадо. И сам ресторан-гриль.",
    tags: [],
    cefrLevel: "A2",
    themes: ["kitchen"],
    quizCorrect: "парилья (гриль)",
    quizOptions: ["парилья (гриль)", "асадо (арг. барбекю)", "духовка", "мангал"],
  },
  {
    language: "es",
    conceptKey: "empanada",
    word: "empanada",
    translationRu: "эмпанада (пирожок)",
    type: "Object",
    rarity: "R",
    baseAtk: 50,
    baseDef: 55,
    colorido: 7,
    flavorText: "Las empanadas salteñas son las mejores, con papa y carne.",
    hint: "«Empanada» от «pan» (хлеб) + приставка em- (внутрь): еда, запечённая в хлебе/тесте. Пирожок.",
    tags: [],
    cefrLevel: "A2",
    themes: ["kitchen"],
    quizCorrect: "эмпанада (пирожок)",
    quizOptions: ["эмпанада (пирожок)", "пирог", "пирожок с начинкой", "фокачча"],
  },
  {
    language: "es",
    conceptKey: "milanesa",
    word: "milanesa",
    translationRu: "миланеса (шницель)",
    type: "Object",
    rarity: "UC",
    baseAtk: 55,
    baseDef: 50,
    colorido: 6,
    flavorText: "Milanesa con puré, la comida de la abuela.",
    hint: "«Milanesa» — буквально «из Милана»: аргентинская версия итальянского cotoletta, панированный шницель. Любимая домашняя еда.",
    tags: [],
    cefrLevel: "A2",
    themes: ["kitchen", "eating-out"],
    quizCorrect: "миланеса (шницель)",
    quizOptions: ["миланеса (шницель)", "котлета", "стейк", "эскалоп"],
  },
  {
    language: "es",
    conceptKey: "medialuna",
    word: "medialuna",
    translationRu: "медиалуна (арг. круассан)",
    type: "Object",
    rarity: "UC",
    baseAtk: 35,
    baseDef: 55,
    colorido: 6,
    flavorText: "Dos medialunas y un café con leche, lo de siempre.",
    hint: "«Medialuna» буквально «полумесяц» по форме: rioplatense версия круассана, обычно более сладкая.",
    tags: [],
    cefrLevel: "A2",
    themes: ["kitchen", "morning-routine"],
    quizCorrect: "медиалуна (арг. круассан)",
    quizOptions: ["медиалуна (арг. круассан)", "круассан", "булочка", "кекс"],
  },
  {
    language: "es",
    conceptKey: "dulce_de_leche",
    word: "dulce de leche",
    translationRu: "дульсе-де-лече (варёная сгущёнка)",
    type: "Object",
    rarity: "R",
    baseAtk: 45,
    baseDef: 60,
    colorido: 8,
    flavorText: "El dulce de leche argentino no tiene rival, con lo que sea.",
    hint: "«Dulce de leche» буквально «молочная сладость»: карамелизованное сгущённое молоко. Национальная сладость Аргентины.",
    tags: [],
    cefrLevel: "A2",
    themes: ["kitchen"],
    quizCorrect: "дульсе-де-лече (варёная сгущёнка)",
    quizOptions: [
      "дульсе-де-лече (варёная сгущёнка)",
      "карамель",
      "джем",
      "сгущённое молоко",
    ],
  },
  {
    language: "es",
    conceptKey: "alfajor",
    word: "alfajor",
    translationRu: "альфахор (печенье с дульсе)",
    type: "Object",
    rarity: "UC",
    baseAtk: 40,
    baseDef: 55,
    colorido: 6,
    flavorText: "Alfajor Havanna con el mate, nada mejor.",
    hint: "«Alfajor» от арабского al-hasú (начинка): два печенья с dulce de leche между ними. Классический арг. десерт.",
    tags: [],
    cefrLevel: "A2",
    themes: ["kitchen"],
    quizCorrect: "альфахор (печенье с дульсе)",
    quizOptions: [
      "альфахор (печенье с дульсе)",
      "печенье",
      "пирожное",
      "шоколадка",
    ],
  },
  {
    language: "es",
    conceptKey: "chimichurri",
    word: "chimichurri",
    translationRu: "чимичурри (соус для асадо)",
    type: "Object",
    rarity: "R",
    baseAtk: 55,
    baseDef: 50,
    colorido: 7,
    flavorText: "Mojá la carne en chimichurri, le da todo el sabor.",
    hint: "«Chimichurri» — классический соус к асадо из петрушки, чеснока, уксуса и масла. Название — rioplatense, этимология спорная.",
    tags: [],
    cefrLevel: "A2",
    themes: ["kitchen"],
    quizCorrect: "чимичурри (соус для асадо)",
    quizOptions: [
      "чимичурри (соус для асадо)",
      "сальса",
      "майонез",
      "кетчуп",
    ],
  },

  // ==========================================================================
  // OBJECTS — напитки базовые (4) — water/coffee/tea + arg тонус
  // ==========================================================================
  {
    language: "es",
    conceptKey: "water",
    word: "agua",
    translationRu: "вода",
    type: "Object",
    rarity: "C",
    baseAtk: 30,
    baseDef: 70,
    colorido: 1,
    flavorText: "¿Me pasás un vaso de agua bien fría?",
    hint: "«Agua» — от латинского aqua, тот же корень что и в русском «аквариум» и английском «aquatic»: вода.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen", "restaurant-abroad", "morning-routine", "body-health"],
    quizCorrect: "вода",
    quizOptions: ["вода", "молоко", "кофе", "сок"],
  },
  {
    language: "es",
    conceptKey: "coffee",
    word: "café",
    translationRu: "кофе",
    type: "Object",
    rarity: "C",
    baseAtk: 45,
    baseDef: 50,
    colorido: 2,
    flavorText: "Un cortado, por favor. ¿Querés algo dulce?",
    hint: "«Café» — интернационализм, родственник русского «кофе» и английского «coffee», все от арабского qahwa.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen", "morning-routine"],
    quizCorrect: "кофе",
    quizOptions: ["кофе", "чай", "мате (сосуд и напиток)", "молоко"],
  },
  {
    language: "es",
    conceptKey: "tea",
    word: "té",
    translationRu: "чай",
    type: "Object",
    rarity: "C",
    baseAtk: 40,
    baseDef: 55,
    colorido: 2,
    flavorText: "Tomate un té con miel, te hace bien para la garganta.",
    hint: "«Té» — интернационализм через китайский «chá» / «tê»: тот же корень что в русском «чай» и английском «tea».",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen", "morning-routine", "body-health"],
    quizCorrect: "чай",
    quizOptions: ["чай", "кофе", "мате (сосуд и напиток)", "молоко"],
  },
  {
    language: "es",
    conceptKey: "food",
    word: "comida",
    translationRu: "еда",
    type: "Object",
    rarity: "C",
    baseAtk: 40,
    baseDef: 55,
    colorido: 2,
    flavorText: "La comida está lista, sentate a la mesa.",
    hint: "«Comida» — существительное от «comer» (есть): буквально «то, что едят». Еда.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen", "eating-out"],
    quizCorrect: "еда",
    quizOptions: ["еда", "обед", "завтрак", "ужин"],
  },

  // ==========================================================================
  // PERSONS — профессии (2)
  // ==========================================================================
  {
    language: "es",
    conceptKey: "cook_person",
    word: "cocinero",
    translationRu: "повар",
    type: "Person",
    rarity: "UC",
    baseAtk: 55,
    baseDef: 55,
    colorido: 3,
    flavorText: "El cocinero del barrio hace las mejores pastas caseras.",
    hint: "«Cocinero» — тот, кто «cocina» (готовит): повар. Производное с -ero (деятель).",
    tags: [],
    cefrLevel: "A2",
    themes: ["kitchen", "professions"],
    quizCorrect: "повар",
    quizOptions: ["повар", "официант", "пекарь", "кондитер"],
  },
  {
    language: "es",
    conceptKey: "baker",
    word: "panadero",
    translationRu: "пекарь",
    type: "Person",
    rarity: "UC",
    baseAtk: 50,
    baseDef: 55,
    colorido: 3,
    flavorText: "El panadero abre a las seis, el pan sale calentito.",
    hint: "«Panadero» — от «pan» (хлеб) + -ero (деятель): тот, кто делает хлеб. Пекарь.",
    tags: [],
    cefrLevel: "A2",
    themes: ["kitchen", "professions"],
    quizCorrect: "пекарь",
    quizOptions: ["пекарь", "повар", "мясник", "кондитер"],
  },

  // ==========================================================================
  // EMOTIONS — голод, жажда, вкус (9)
  // ==========================================================================
  {
    language: "es",
    conceptKey: "hungry_state",
    word: "hambriento",
    translationRu: "голодный",
    type: "Emotion",
    rarity: "UC",
    baseAtk: 55,
    baseDef: 45,
    colorido: 3,
    flavorText: "Vengo hambriento del gimnasio, ¿hay algo para morfar?",
    hint: "«Hambriento» — прилагательное от «hambre» (голод): прилагательное состояния, голодный.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen", "feelings"],
    quizCorrect: "голодный",
    quizOptions: ["голодный", "сытый", "сонный", "уставший"],
  },
  {
    language: "es",
    conceptKey: "thirsty",
    word: "sediento",
    translationRu: "жаждущий / хочет пить",
    type: "Emotion",
    rarity: "UC",
    baseAtk: 50,
    baseDef: 45,
    colorido: 3,
    flavorText: "Estoy sediento, dame un vaso de agua.",
    hint: "«Sediento» — прилагательное от «sed» (жажда): прилагательное состояния, хочет пить.",
    tags: [],
    cefrLevel: "A2",
    themes: ["kitchen", "feelings", "body-health"],
    quizCorrect: "жаждущий / хочет пить",
    quizOptions: ["жаждущий / хочет пить", "голодный", "сытый", "уставший"],
  },
  {
    language: "es",
    conceptKey: "full_stomach",
    word: "lleno",
    translationRu: "сытый / полный",
    type: "Emotion",
    rarity: "C",
    baseAtk: 40,
    baseDef: 60,
    colorido: 2,
    flavorText: "No puedo más, estoy lleno, comí demasiado.",
    hint: "«Lleno» — прилагательное «full» (полный). В контексте еды — сытый, «наполненный».",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen", "feelings"],
    quizCorrect: "сытый / полный",
    quizOptions: ["сытый / полный", "голодный", "пустой", "жаждущий / хочет пить"],
  },
  {
    language: "es",
    conceptKey: "tasty_rico",
    word: "rico",
    translationRu: "вкусный (арг.)",
    type: "Emotion",
    rarity: "C",
    baseAtk: 50,
    baseDef: 50,
    colorido: 3,
    flavorText: "¡Qué rico que está este flan, estás hecha una cocinera!",
    hint: "«Rico» буквально «богатый», но в Rioplatense про еду = вкусный, насыщенный. Не путать со значением «богатый деньгами».",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen", "feelings", "eating-out"],
    quizCorrect: "вкусный (арг.)",
    quizOptions: ["вкусный (арг.)", "богатый", "солёный", "сладкий"],
  },
  {
    language: "es",
    conceptKey: "delicious",
    word: "sabroso",
    translationRu: "вкусный / ароматный",
    type: "Emotion",
    rarity: "UC",
    baseAtk: 45,
    baseDef: 55,
    colorido: 3,
    flavorText: "El locro estaba sabrosísimo, con mucho sabor.",
    hint: "«Sabroso» — от «sabor» (вкус) + -oso (полный): полный вкуса, вкусный, ароматный.",
    tags: [],
    cefrLevel: "A2",
    themes: ["kitchen", "eating-out", "feelings"],
    quizCorrect: "вкусный / ароматный",
    quizOptions: ["вкусный / ароматный", "вкусный (арг.)", "солёный", "сладкий"],
  },
  {
    language: "es",
    conceptKey: "salty",
    word: "salado",
    translationRu: "солёный",
    type: "Emotion",
    rarity: "C",
    baseAtk: 45,
    baseDef: 50,
    colorido: 2,
    flavorText: "Me quedó un poco salado, le puse sal de más.",
    hint: "«Salado» — буквально «посоленный», прилагательное от «sal» (соль). Солёный.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen", "feelings"],
    quizCorrect: "солёный",
    quizOptions: ["солёный", "сладкий", "горький", "острый"],
  },
  {
    language: "es",
    conceptKey: "sweet",
    word: "dulce",
    translationRu: "сладкий",
    type: "Emotion",
    rarity: "C",
    baseAtk: 40,
    baseDef: 55,
    colorido: 2,
    flavorText: "Me gusta el café dulce, con dos de azúcar.",
    hint: "«Dulce» — родственник английского «dulcet» (приятный) и «dolce» в музыке: сладкий на вкус.",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen", "feelings"],
    quizCorrect: "сладкий",
    quizOptions: ["сладкий", "солёный", "горький", "кислый"],
  },
  {
    language: "es",
    conceptKey: "bitter",
    word: "amargo",
    translationRu: "горький",
    type: "Emotion",
    rarity: "UC",
    baseAtk: 45,
    baseDef: 50,
    colorido: 4,
    flavorText: "El mate amargo es como le gusta al viejo, sin azúcar.",
    hint: "«Amargo» — от латинского amarus. Горький, резкий на вкус. В Rioplatense про мате без сахара.",
    tags: [],
    cefrLevel: "A2",
    themes: ["kitchen", "feelings"],
    quizCorrect: "горький",
    quizOptions: ["горький", "сладкий", "солёный", "кислый"],
  },
  {
    language: "es",
    conceptKey: "spicy",
    word: "picante",
    translationRu: "острый (о еде)",
    type: "Emotion",
    rarity: "UC",
    baseAtk: 55,
    baseDef: 45,
    colorido: 4,
    flavorText: "El aji molido está bravo, muy picante para mí.",
    hint: "«Picante» — причастие от «picar» (колоть): еда, которая «колет» язык. Острая.",
    tags: [],
    cefrLevel: "A2",
    themes: ["kitchen", "feelings"],
    quizCorrect: "острый (о еде)",
    quizOptions: ["острый (о еде)", "горький", "солёный", "кислый"],
  },

  // ==========================================================================
  // EXPRESSIONS — культурные обороты (4)
  // ==========================================================================
  {
    language: "es",
    conceptKey: "bon_appetit",
    word: "buen provecho",
    translationRu: "приятного аппетита",
    type: "Expression",
    rarity: "UC",
    baseAtk: 50,
    baseDef: 50,
    colorido: 5,
    flavorText: "—Buen provecho. —Gracias, igualmente.",
    hint: "«Buen provecho» буквально «хорошая польза»: пожелание перед едой. Эквивалент «приятного аппетита» и «bon appétit».",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen", "eating-out", "greetings-courtesy"],
    quizCorrect: "приятного аппетита",
    quizOptions: ["приятного аппетита", "спасибо", "до свидания", "за здоровье (тост)"],
  },
  {
    language: "es",
    conceptKey: "cheers_toast",
    word: "¡salud!",
    translationRu: "за здоровье! (тост)",
    type: "Expression",
    rarity: "UC",
    baseAtk: 55,
    baseDef: 45,
    colorido: 5,
    flavorText: "¡Salud! Por los que estamos y por los que no pudieron venir.",
    hint: "«Salud» буквально «здоровье». Используется и как тост («за здоровье»), и когда кто-то чихнул («будь здоров»).",
    tags: [],
    cefrLevel: "A1",
    themes: ["kitchen", "eating-out", "greetings-courtesy", "party-celebration"],
    quizCorrect: "за здоровье! (тост)",
    quizOptions: ["за здоровье! (тост)", "приятного аппетита", "спасибо", "здравствуй"],
  },
  {
    language: "es",
    conceptKey: "sobremesa",
    word: "la sobremesa",
    translationRu: "разговор после еды (посиделки за столом)",
    type: "Expression",
    rarity: "R",
    baseAtk: 55,
    baseDef: 60,
    colorido: 7,
    flavorText: "Nos quedamos tres horas en la sobremesa hablando de cualquier cosa.",
    hint: "«Sobremesa» = sobre (над/после) + mesa (стол): время после еды, когда остаются за столом болтать. Важный культурный концепт.",
    tags: [],
    cefrLevel: "A2",
    themes: ["kitchen", "eating-out"],
    quizCorrect: "разговор после еды (посиделки за столом)",
    quizOptions: [
      "разговор после еды (посиделки за столом)",
      "десерт",
      "чаевые",
      "закуска",
    ],
  },
  {
    language: "es",
    conceptKey: "morfi",
    word: "morfi",
    translationRu: "жрачка (лунфардо)",
    type: "Expression",
    rarity: "SR",
    baseAtk: 60,
    baseDef: 45,
    colorido: 8,
    flavorText: "Tengo hambre, ¿hay morfi en la heladera?",
    hint: "«Morfi» — lunfardo от итальянского «morfiare» (жрать): еда на сленге. В Аргентине абсолютно нормально в неформальной речи.",
    tags: [],
    cefrLevel: "B1",
    themes: ["kitchen", "slang-rioplatense"],
    quizCorrect: "жрачка (лунфардо)",
    quizOptions: ["жрачка (лунфардо)", "еда", "закуска", "блюдо"],
  },
  {
    language: "es",
    conceptKey: "eat_slang_morfar",
    word: "morfar",
    translationRu: "жрать / хавать (лунфардо)",
    type: "Action",
    rarity: "SR",
    baseAtk: 65,
    baseDef: 40,
    colorido: 8,
    flavorText: "—¿Vamos a morfar algo? —Dale, muero de hambre.",
    hint: "«Morfar» — глагол-парный к «morfi», lunfardo от итальянского «morfiare»: есть на сленге. Грубее чем «comer».",
    tags: [],
    cefrLevel: "B1",
    themes: ["kitchen", "slang-rioplatense"],
    quizCorrect: "жрать / хавать (лунфардо)",
    quizOptions: [
      "жрать / хавать (лунфардо)",
      "есть (кушать)",
      "пить (арг.) / брать",
      "жевать",
    ],
  },
];
