import type { SeedWord } from "./seed-words.types.js";

export const RARE_WORDS: SeedWord[] = [
  // Places (3)
  {
    language: "es",
    conceptKey: "neighborhood",
    word: "barrio",
    translationRu: "район",
    type: "Place",
    rarity: "R",
    baseAtk: 60,
    baseDef: 55,
    colorido: 3,
    flavorText: "Este barrio es tranquilo, pero de noche se pone raro.",
    hint: "«Barrio» звучит как барьер между кварталами — отдельный район.",
    tags: ["ciudad", "vida"],
    quizCorrect: "район",
    quizOptions: ["район", "город", "улица", "площадь"],
  },
  {
    language: "es",
    conceptKey: "border",
    word: "frontera",
    translationRu: "граница",
    type: "Place",
    rarity: "R",
    baseAtk: 55,
    baseDef: 65,
    colorido: 3,
    flavorText: "En la frontera nos revisaron el auto.",
    hint: "«Frontera» напоминает frontier — граница.",
    tags: ["viajes", "documentos"],
    quizCorrect: "граница",
    quizOptions: ["граница", "станция", "аэропорт", "парк"],
  },
  {
    language: "es",
    conceptKey: "building",
    word: "edificio",
    translationRu: "здание",
    type: "Place",
    rarity: "R",
    baseAtk: 50,
    baseDef: 70,
    colorido: 3,
    flavorText: "El edificio es viejo, pero tiene un ascensor enorme.",
    hint: "«Edificio» — как edifice, большое здание.",
    tags: ["ciudad", "hogar"],
    quizCorrect: "здание",
    quizOptions: ["здание", "комната", "улица", "магазин"],
  },

  // Persons (3)
  {
    language: "es",
    conceptKey: "partner",
    word: "pareja",
    translationRu: "пара",
    type: "Person",
    rarity: "R",
    baseAtk: 55,
    baseDef: 60,
    colorido: 3,
    flavorText: "Mi pareja me banca en todas.",
    hint: "«Pareja» звучит как «парочка» — значит пара.",
    tags: ["relaciones", "conversación"],
    quizCorrect: "пара",
    quizOptions: ["пара", "друг", "сосед", "клиент"],
  },
  {
    language: "es",
    conceptKey: "stranger",
    word: "desconocido",
    translationRu: "незнакомец",
    type: "Person",
    rarity: "R",
    baseAtk: 60,
    baseDef: 55,
    colorido: 3,
    flavorText: "Un desconocido me preguntó la hora en la calle.",
    hint: "«Desconocido» будто человек без кода доступа — незнакомец.",
    tags: ["ciudad", "relaciones"],
    quizCorrect: "незнакомец",
    quizOptions: ["незнакомец", "сосед", "учитель", "коллега"],
  },
  {
    language: "es",
    conceptKey: "guest",
    word: "invitado",
    translationRu: "гость",
    type: "Person",
    rarity: "R",
    baseAtk: 55,
    baseDef: 60,
    colorido: 3,
    flavorText: "Hoy tenemos invitados, así que limpié todo.",
    hint: "«Invitado» связан с invitation: раз пригласили, значит гость.",
    tags: ["hogar", "fiesta"],
    quizCorrect: "гость",
    quizOptions: ["гость", "клиент", "начальник", "водитель"],
  },

  // Actions (4)
  {
    language: "es",
    conceptKey: "lose",
    word: "perder",
    translationRu: "терять / проигрывать",
    type: "Action",
    rarity: "R",
    baseAtk: 65,
    baseDef: 50,
    colorido: 4,
    flavorText: "No quiero perder otra vez, me da bronca.",
    hint: "«Perder» — как «потерял и пролетел»: терять или проигрывать.",
    tags: ["verbo", "vida"],
    quizCorrect: "терять / проигрывать",
    quizOptions: ["терять / проигрывать", "находить", "выигрывать", "ждать"],
  },
  {
    language: "es",
    conceptKey: "take_advantage",
    word: "aprovechar",
    translationRu: "воспользоваться",
    type: "Action",
    rarity: "R",
    baseAtk: 60,
    baseDef: 55,
    colorido: 3,
    flavorText: "Aprovechá que está barato y comprá ahora.",
    hint: "«Aprovechar» — будто ухватить и выжать пользу, то есть воспользоваться.",
    tags: ["verbo", "compras"],
    quizCorrect: "воспользоваться",
    quizOptions: ["воспользоваться", "терять / проигрывать", "ждать", "спать"],
  },
  {
    language: "es",
    conceptKey: "convince",
    word: "convencer",
    translationRu: "убеждать",
    type: "Action",
    rarity: "R",
    baseAtk: 65,
    baseDef: 55,
    colorido: 3,
    flavorText: "No pude convencerlo, estaba decidido.",
    hint: "«Convencer» почти как convince — убеждать.",
    tags: ["verbo", "comunicación"],
    quizCorrect: "убеждать",
    quizOptions: ["убеждать", "слушать", "ждать", "учиться"],
  },
  {
    language: "es",
    conceptKey: "recognize",
    word: "reconocer",
    translationRu: "узнавать",
    type: "Action",
    rarity: "R",
    baseAtk: 55,
    baseDef: 65,
    colorido: 3,
    flavorText: "Te reconocí por la voz, aunque estaba oscuro.",
    hint: "«Reconocer» напоминает recognize — узнавать.",
    tags: ["verbo", "vida"],
    quizCorrect: "узнавать",
    quizOptions: ["узнавать", "забывать", "искать", "покупать"],
  },

  // Objects (4)
  {
    language: "es",
    conceptKey: "meeting",
    word: "reunión",
    translationRu: "встреча (совещание)",
    type: "Object",
    rarity: "R",
    baseAtk: 55,
    baseDef: 70,
    colorido: 3,
    flavorText: "Tengo una reunión a las nueve, no me cuelgo.",
    hint: "«Reunión» — это reunion, встреча и сбор вместе.",
    tags: ["trabajo", "formal"],
    quizCorrect: "встреча (совещание)",
    quizOptions: ["встреча (совещание)", "путешествие", "подарок", "страх"],
  },
  {
    language: "es",
    conceptKey: "opportunity",
    word: "oportunidad",
    translationRu: "возможность",
    type: "Object",
    rarity: "R",
    baseAtk: 60,
    baseDef: 60,
    colorido: 3,
    flavorText: "Es una oportunidad única, no la dejes pasar.",
    hint: "«Oportunidad» почти как opportunity — возможность.",
    tags: ["vida", "formal"],
    quizCorrect: "возможность",
    quizOptions: ["возможность", "встреча (совещание)", "работа", "карта"],
  },
  {
    language: "es",
    conceptKey: "decision",
    word: "decisión",
    translationRu: "решение",
    type: "Object",
    rarity: "R",
    baseAtk: 55,
    baseDef: 65,
    colorido: 3,
    flavorText: "Tomé una decisión y no pienso cambiarla.",
    hint: "«Decisión» — как decision, решение.",
    tags: ["vida", "formal"],
    quizCorrect: "решение",
    quizOptions: ["решение", "возможность", "встреча (совещание)", "подарок"],
  },
  {
    language: "es",
    conceptKey: "memory",
    word: "recuerdo",
    translationRu: "воспоминание",
    type: "Object",
    rarity: "R",
    baseAtk: 55,
    baseDef: 60,
    colorido: 4,
    flavorText: "Ese lugar me trae recuerdos de mi infancia.",
    hint: "«Recuerdo» — будто record в голове, воспоминание.",
    tags: ["vida", "emociones"],
    quizCorrect: "воспоминание",
    quizOptions: ["воспоминание", "возможность", "страх", "терпение"],
  },

  // Emotions (3)
  {
    language: "es",
    conceptKey: "pride",
    word: "orgullo",
    translationRu: "гордость",
    type: "Emotion",
    rarity: "R",
    baseAtk: 60,
    baseDef: 60,
    colorido: 4,
    flavorText: "Siento orgullo por lo que lograste.",
    hint: "«Orgullo» рычит гордо и с грудью вперёд — гордость.",
    tags: ["emociones", "formal"],
    quizCorrect: "гордость",
    quizOptions: ["гордость", "страх", "радость", "стыд"],
  },
  {
    language: "es",
    conceptKey: "anxiety",
    word: "ansiedad",
    translationRu: "тревога",
    type: "Emotion",
    rarity: "R",
    baseAtk: 55,
    baseDef: 70,
    colorido: 3,
    flavorText: "Me agarró ansiedad antes de la entrevista.",
    hint: "«Ansiedad» напоминает anxiety — тревога.",
    tags: ["emociones", "trabajo"],
    quizCorrect: "тревога",
    quizOptions: ["тревога", "радость", "спокойствие", "скука"],
  },
  {
    language: "es",
    conceptKey: "relief",
    word: "alivio",
    translationRu: "облегчение",
    type: "Emotion",
    rarity: "R",
    baseAtk: 50,
    baseDef: 70,
    colorido: 3,
    flavorText: "Cuando llegó el mensaje sentí un alivio enorme.",
    hint: "«Alivio» — как лёгкий выдох, когда отпустило: облегчение.",
    tags: ["emociones", "vida"],
    quizCorrect: "облегчение",
    quizOptions: ["облегчение", "страх", "стыд", "сюрприз"],
  },

  // Expressions (3)
  {
    language: "es",
    conceptKey: "suddenly",
    word: "de repente",
    translationRu: "вдруг",
    type: "Expression",
    rarity: "R",
    baseAtk: 55,
    baseDef: 65,
    colorido: 4,
    flavorText: "Íbamos charlando y de repente se cortó la luz.",
    hint: "«De repente» — будто реплика врывается в тишину: вдруг.",
    tags: ["conversación", "tiempo"],
    quizCorrect: "вдруг",
    quizOptions: ["вдруг", "потом", "сейчас", "никогда"],
  },
  {
    language: "es",
    conceptKey: "on_purpose",
    word: "a propósito",
    translationRu: "нарочно",
    type: "Expression",
    rarity: "R",
    baseAtk: 55,
    baseDef: 60,
    colorido: 3,
    flavorText: "¿Lo hiciste a propósito o fue sin querer?",
    hint: "«A propósito» — как «по замыслу», значит нарочно.",
    tags: ["conversación", "vida"],
    quizCorrect: "нарочно",
    quizOptions: ["нарочно", "случайно", "вдруг", "сразу"],
  },
  {
    language: "es",
    conceptKey: "no_way",
    word: "ni loco",
    translationRu: "ни за что",
    type: "Expression",
    rarity: "R",
    baseAtk: 60,
    baseDef: 55,
    colorido: 4,
    flavorText: "Ni loco me meto en ese quilombo.",
    hint: "«Ni loco» — даже сумасшедшим не согласился бы: ни за что.",
    tags: ["conversación", "slang"],
    quizCorrect: "ни за что",
    quizOptions: ["ни за что", "может быть", "конечно", "пожалуйста"],
  },
];

