export type SeedWord = {
  language: "es";
  word: string;
  translationRu: string;
  type: "Person" | "Place" | "Action" | "Object" | "Emotion" | "Expression";
  rarity: "C" | "UC" | "R" | "SR";
  baseAtk: number;
  baseDef: number;
  colorido: number;
  flavorText: string;
  hint: string;
  tags: string[];
  canEvolve?: boolean;
  imagePrompt?: string | null;
  quizCorrect: string;
  quizOptions: [string, string, string, string];
  evolutionData?: unknown | null;
};

export const WORDS: SeedWord[] = [
  // C (15)
  {
    language: "es",
    word: "casa",
    translationRu: "дом",
    type: "Place",
    rarity: "C",
    baseAtk: 40,
    baseDef: 60,
    colorido: 2,
    flavorText: "—¿Dónde vivís? —En casa de mis viejos, por ahora.",
    hint: "Базовое слово: 'дом'. Часто встречается в первых уроках.",
    tags: ["básico", "vivienda"],
    quizCorrect: "дом",
    quizOptions: ["дом", "машина", "улица", "город"],
  },
  {
    language: "es",
    word: "escuela",
    translationRu: "школа",
    type: "Place",
    rarity: "C",
    baseAtk: 35,
    baseDef: 55,
    colorido: 2,
    flavorText: "Mi hermana va a la escuela temprano.",
    hint: "Слово женского рода; часто употребляется с артиклем 'la'.",
    tags: ["básico", "educación"],
    quizCorrect: "школа",
    quizOptions: ["школа", "работа", "магазин", "парк"],
  },
  {
    language: "es",
    word: "calle",
    translationRu: "улица",
    type: "Place",
    rarity: "C",
    baseAtk: 45,
    baseDef: 40,
    colorido: 2,
    flavorText: "La calle está vacía a esta hora.",
    hint: "Устойчивое: 'en la calle' — на улице.",
    tags: ["básico", "ciudad"],
    quizCorrect: "улица",
    quizOptions: ["улица", "окно", "вода", "книга"],
  },
  {
    language: "es",
    word: "amigo",
    translationRu: "друг",
    type: "Person",
    rarity: "C",
    baseAtk: 50,
    baseDef: 35,
    colorido: 2,
    flavorText: "—Che, ¿venís? —Sí, voy con un amigo.",
    hint: "Форма мн. числа: amigos; женская: amiga.",
    tags: ["básico", "relaciones"],
    quizCorrect: "друг",
    quizOptions: ["друг", "враг", "учитель", "брат"],
  },
  {
    language: "es",
    word: "madre",
    translationRu: "мама",
    type: "Person",
    rarity: "C",
    baseAtk: 45,
    baseDef: 55,
    colorido: 2,
    flavorText: "Mi madre cocina muy rico.",
    hint: "Часто употребляется как 'mi madre' — моя мама.",
    tags: ["familia", "básico"],
    quizCorrect: "мама",
    quizOptions: ["мама", "папа", "сестра", "дочь"],
  },
  {
    language: "es",
    word: "doctor",
    translationRu: "врач",
    type: "Person",
    rarity: "C",
    baseAtk: 55,
    baseDef: 45,
    colorido: 2,
    flavorText: "El doctor me dijo que descanse.",
    hint: "Женская форма: doctora.",
    tags: ["profesión", "salud"],
    quizCorrect: "врач",
    quizOptions: ["врач", "водитель", "повар", "продавец"],
  },
  {
    language: "es",
    word: "comer",
    translationRu: "есть (кушать)",
    type: "Action",
    rarity: "C",
    baseAtk: 60,
    baseDef: 35,
    colorido: 2,
    flavorText: "Vamos a comer algo antes de salir.",
    hint: "Инфинитив. Настоящее: como, comes, come…",
    tags: ["básico", "verbo"],
    quizCorrect: "есть (кушать)",
    quizOptions: ["есть (кушать)", "спать", "пить", "бежать"],
  },
  {
    language: "es",
    word: "hablar",
    translationRu: "говорить",
    type: "Action",
    rarity: "C",
    baseAtk: 55,
    baseDef: 40,
    colorido: 2,
    flavorText: "Necesito hablar contigo un momento.",
    hint: "Инфинитив. Часто: hablar español — говорить по-испански.",
    tags: ["básico", "verbo"],
    quizCorrect: "говорить",
    quizOptions: ["говорить", "читать", "писать", "слушать"],
  },
  {
    language: "es",
    word: "leer",
    translationRu: "читать",
    type: "Action",
    rarity: "C",
    baseAtk: 50,
    baseDef: 45,
    colorido: 2,
    flavorText: "Me gusta leer por la noche.",
    hint: "Инфинитив. Прош.: leí; сущ.: lectura.",
    tags: ["básico", "verbo"],
    quizCorrect: "читать",
    quizOptions: ["читать", "спать", "есть", "плавать"],
  },
  {
    language: "es",
    word: "agua",
    translationRu: "вода",
    type: "Object",
    rarity: "C",
    baseAtk: 40,
    baseDef: 70,
    colorido: 2,
    flavorText: "¿Me das un vaso de agua, por favor?",
    hint: "Слово женского рода, но с артиклем 'el' в единственном: el agua.",
    tags: ["básico", "objeto"],
    quizCorrect: "вода",
    quizOptions: ["вода", "огонь", "воздух", "земля"],
  },
  {
    language: "es",
    word: "libro",
    translationRu: "книга",
    type: "Object",
    rarity: "C",
    baseAtk: 45,
    baseDef: 55,
    colorido: 2,
    flavorText: "Este libro es muy interesante.",
    hint: "Мн. число: libros.",
    tags: ["básico", "objeto"],
    quizCorrect: "книга",
    quizOptions: ["книга", "стол", "дверь", "окно"],
  },
  {
    language: "es",
    word: "mesa",
    translationRu: "стол",
    type: "Object",
    rarity: "C",
    baseAtk: 35,
    baseDef: 75,
    colorido: 2,
    flavorText: "Dejá las llaves sobre la mesa.",
    hint: "Слово женского рода: la mesa.",
    tags: ["básico", "hogar"],
    quizCorrect: "стол",
    quizOptions: ["стол", "стул", "кровать", "шкаф"],
  },
  {
    language: "es",
    word: "feliz",
    translationRu: "счастливый",
    type: "Emotion",
    rarity: "C",
    baseAtk: 55,
    baseDef: 45,
    colorido: 2,
    flavorText: "Estoy muy feliz hoy.",
    hint: "Используется с estar: estar feliz — быть счастливым.",
    tags: ["básico", "эмоции"],
    quizCorrect: "счастливый",
    quizOptions: ["счастливый", "грустный", "злой", "уставший"],
  },
  {
    language: "es",
    word: "triste",
    translationRu: "грустный",
    type: "Emotion",
    rarity: "C",
    baseAtk: 50,
    baseDef: 50,
    colorido: 2,
    flavorText: "No estés triste, todo va a estar bien.",
    hint: "Часто: estar triste — быть грустным.",
    tags: ["básico", "эмоции"],
    quizCorrect: "грустный",
    quizOptions: ["грустный", "счастливый", "голодный", "тёплый"],
  },

  // UC (8)
  {
    language: "es",
    word: "trabajo",
    translationRu: "работа",
    type: "Object",
    rarity: "UC",
    baseAtk: 55,
    baseDef: 75,
    colorido: 3,
    flavorText: "Tengo mucho trabajo esta semana.",
    hint: "Также: 'el trabajo' — работа/место работы.",
    tags: ["básico", "vida"],
    quizCorrect: "работа",
    quizOptions: ["работа", "школа", "дом", "парк"],
  },
  {
    language: "es",
    word: "jefe",
    translationRu: "начальник",
    type: "Person",
    rarity: "UC",
    baseAtk: 80,
    baseDef: 55,
    colorido: 3,
    flavorText: "Mi jefe quiere hablar conmigo.",
    hint: "Женская форма: jefa.",
    tags: ["profesión", "vida"],
    quizCorrect: "начальник",
    quizOptions: ["начальник", "друг", "врач", "учитель"],
  },
  {
    language: "es",
    word: "viaje",
    translationRu: "путешествие",
    type: "Object",
    rarity: "UC",
    baseAtk: 70,
    baseDef: 65,
    colorido: 3,
    flavorText: "Este viaje fue increíble.",
    hint: "Слово мужского рода: el viaje.",
    tags: ["viajar", "vida"],
    quizCorrect: "путешествие",
    quizOptions: ["путешествие", "письмо", "встреча", "погода"],
  },
  {
    language: "es",
    word: "correr",
    translationRu: "бегать",
    type: "Action",
    rarity: "UC",
    baseAtk: 90,
    baseDef: 50,
    colorido: 3,
    flavorText: "Me gusta correr por el parque.",
    hint: "Инфинитив. Наст.: corro, corres, corre…",
    tags: ["deporte", "verbo"],
    quizCorrect: "бегать",
    quizOptions: ["бегать", "прыгать", "плавать", "спать"],
  },
  {
    language: "es",
    word: "escuchar",
    translationRu: "слушать",
    type: "Action",
    rarity: "UC",
    baseAtk: 75,
    baseDef: 70,
    colorido: 3,
    flavorText: "¿Podés escucharme un segundo?",
    hint: "Часто: escuchar música — слушать музыку.",
    tags: ["básico", "verbo"],
    quizCorrect: "слушать",
    quizOptions: ["слушать", "говорить", "читать", "писать"],
  },
  {
    language: "es",
    word: "miedo",
    translationRu: "страх",
    type: "Emotion",
    rarity: "UC",
    baseAtk: 85,
    baseDef: 55,
    colorido: 3,
    flavorText: "Tengo miedo de la oscuridad.",
    hint: "Фраза: tener miedo — бояться.",
    tags: ["эмоции", "básico"],
    quizCorrect: "страх",
    quizOptions: ["страх", "радость", "сон", "голод"],
  },
  {
    language: "es",
    word: "alegría",
    translationRu: "радость",
    type: "Emotion",
    rarity: "UC",
    baseAtk: 70,
    baseDef: 80,
    colorido: 3,
    flavorText: "Fue una noticia llena de alegría.",
    hint: "Сущ. женского рода: la alegría.",
    tags: ["эмоции", "vida"],
    quizCorrect: "радость",
    quizOptions: ["радость", "страх", "злость", "грусть"],
  },
  {
    language: "es",
    word: "por favor",
    translationRu: "пожалуйста",
    type: "Expression",
    rarity: "UC",
    baseAtk: 60,
    baseDef: 90,
    colorido: 3,
    flavorText: "Un café, por favor.",
    hint: "Вежливое слово. Также отвечает на благодарность: 'de nada'.",
    tags: ["expresión", "básico"],
    quizCorrect: "пожалуйста",
    quizOptions: ["пожалуйста", "спасибо", "извини", "привет"],
  },

  // R (5)
  {
    language: "es",
    word: "orgullo",
    translationRu: "гордость",
    type: "Emotion",
    rarity: "R",
    baseAtk: 120,
    baseDef: 90,
    colorido: 5,
    flavorText: "Siento orgullo por lo que lograste.",
    hint: "Сущ. мужского рода: el orgullo.",
    tags: ["эмоции", "formal"],
    quizCorrect: "гордость",
    quizOptions: ["гордость", "страх", "радость", "злость"],
  },
  {
    language: "es",
    word: "perder",
    translationRu: "терять / проигрывать",
    type: "Action",
    rarity: "R",
    baseAtk: 140,
    baseDef: 75,
    colorido: 5,
    flavorText: "No quiero perder otra vez.",
    hint: "Значение зависит от контекста: терять (ключи) или проигрывать (игру).",
    tags: ["verbo", "vida"],
    quizCorrect: "терять / проигрывать",
    quizOptions: ["терять / проигрывать", "находить", "выигрывать", "прыгать"],
  },
  {
    language: "es",
    word: "reunión",
    translationRu: "встреча (совещание)",
    type: "Object",
    rarity: "R",
    baseAtk: 110,
    baseDef: 120,
    colorido: 5,
    flavorText: "Tengo una reunión a las nueve.",
    hint: "Сущ. женского рода: la reunión.",
    tags: ["trabajo", "formal"],
    quizCorrect: "встреча (совещание)",
    quizOptions: ["встреча (совещание)", "праздник", "путешествие", "сон"],
  },
  {
    language: "es",
    word: "barrio",
    translationRu: "район",
    type: "Place",
    rarity: "R",
    baseAtk: 125,
    baseDef: 85,
    colorido: 5,
    flavorText: "Este barrio es tranquilo.",
    hint: "Сущ. мужского рода: el barrio.",
    tags: ["ciudad", "vida"],
    quizCorrect: "район",
    quizOptions: ["район", "страна", "улица", "дом"],
  },
  {
    language: "es",
    word: "de repente",
    translationRu: "вдруг",
    type: "Expression",
    rarity: "R",
    baseAtk: 100,
    baseDef: 140,
    colorido: 5,
    flavorText: "De repente empezó a llover.",
    hint: "Устойчивое наречное выражение.",
    tags: ["expresión", "básico"],
    quizCorrect: "вдруг",
    quizOptions: ["вдруг", "потом", "сейчас", "никогда"],
  },

  // SR (2)
  {
    language: "es",
    word: "cargar con",
    translationRu: "нести ответственность за",
    type: "Action",
    rarity: "SR",
    baseAtk: 160,
    baseDef: 120,
    colorido: 7,
    flavorText: "No quiero cargar con todo yo solo.",
    hint: "Фразовый глагол: 'cargar con' = тащить на себе (в т.ч. ответственность).",
    tags: ["idioma", "formal"],
    quizCorrect: "нести ответственность за",
    quizOptions: ["нести ответственность за", "убегать", "забывать", "путешествовать"],
  },
  {
    language: "es",
    word: "estar en las nubes",
    translationRu: "витать в облаках",
    type: "Expression",
    rarity: "SR",
    baseAtk: 80,
    baseDef: 55,
    colorido: 7,
    flavorText: "Perdón, estaba en las nubes y no escuché tu pregunta.",
    hint: "Идиома: быть рассеянным/мечтать.",
    tags: ["idioma", "conversación"],
    quizCorrect: "витать в облаках",
    quizOptions: ["витать в облаках", "быть голодным", "быть усталым", "быть злым"],
  },
];

