import type { SeedWord } from "./seed-words.types.js";

export const COMMON_WORDS: SeedWord[] = [
  // Places (12)
  {
    language: "es",
    conceptKey: "house",
    word: "casa",
    translationRu: "дом",
    type: "Place",
    rarity: "C",
    baseAtk: 45,
    baseDef: 55,
    colorido: 2,
    flavorText: "—¿Dónde vivís? —En casa de mis viejos, por ahora.",
    hint: "«Casa» звучит как «касса»: после дел все деньги несёшь домой, в дом.",
    tags: ["vivienda", "básico"],
    quizCorrect: "дом",
    quizOptions: ["дом", "школа", "магазин", "парк"],
  },
  {
    language: "es",
    conceptKey: "school",
    word: "escuela",
    translationRu: "школа",
    type: "Place",
    rarity: "C",
    baseAtk: 40,
    baseDef: 55,
    colorido: 2,
    flavorText: "Mi hermana va a la escuela temprano.",
    hint: "«Escuela» — родственница school: школьный звук сразу ведёт к школе.",
    tags: ["educación", "básico"],
    quizCorrect: "школа",
    quizOptions: ["школа", "больница", "банк", "площадь"],
  },
  {
    language: "es",
    conceptKey: "street",
    word: "calle",
    translationRu: "улица",
    type: "Place",
    rarity: "C",
    baseAtk: 50,
    baseDef: 40,
    colorido: 2,
    flavorText: "La calle está vacía a esta hora.",
    hint: "«Calle» напоминает «аллею»: идёшь по аллее, значит по улице.",
    tags: ["ciudad", "básico"],
    quizCorrect: "улица",
    quizOptions: ["улица", "окно", "книга", "вода"],
  },
  {
    language: "es",
    conceptKey: "city",
    word: "ciudad",
    translationRu: "город",
    type: "Place",
    rarity: "C",
    baseAtk: 55,
    baseDef: 45,
    colorido: 2,
    flavorText: "La ciudad de noche tiene otra energía.",
    hint: "«Ciudad» — кузина city: общий корень ведёт прямо в город.",
    tags: ["ciudad", "básico"],
    quizCorrect: "город",
    quizOptions: ["город", "деревня", "улица", "дом"],
  },
  {
    language: "es",
    conceptKey: "park",
    word: "parque",
    translationRu: "парк",
    type: "Place",
    rarity: "C",
    baseAtk: 45,
    baseDef: 50,
    colorido: 2,
    flavorText: "Vamos al parque un rato, hace lindo.",
    hint: "«Parque» почти как «парк» — чистый интернационализм.",
    tags: ["ciudad", "tiempo_libre"],
    quizCorrect: "парк",
    quizOptions: ["парк", "магазин", "офис", "аэропорт"],
  },
  {
    language: "es",
    conceptKey: "shop",
    word: "tienda",
    translationRu: "магазин",
    type: "Place",
    rarity: "C",
    baseAtk: 50,
    baseDef: 45,
    colorido: 2,
    flavorText: "Paso por la tienda y vuelvo.",
    hint: "«Tienda» звучит как тент над лавкой — вспоминается магазин.",
    tags: ["compras", "básico"],
    quizCorrect: "магазин",
    quizOptions: ["магазин", "школа", "площадь", "улица"],
  },
  {
    language: "es",
    conceptKey: "market",
    word: "mercado",
    translationRu: "рынок",
    type: "Place",
    rarity: "C",
    baseAtk: 50,
    baseDef: 50,
    colorido: 2,
    flavorText: "En el mercado la fruta está más barata.",
    hint: "«Mercado» похоже на market — сразу рынок.",
    tags: ["compras", "comida"],
    quizCorrect: "рынок",
    quizOptions: ["рынок", "банк", "больница", "комната"],
  },
  {
    language: "es",
    conceptKey: "hospital",
    word: "hospital",
    translationRu: "больница",
    type: "Place",
    rarity: "C",
    baseAtk: 35,
    baseDef: 70,
    colorido: 1,
    flavorText: "Lo llevaron al hospital por precaución.",
    hint: "«Hospital» почти как «госпиталь» — значит больница.",
    tags: ["salud", "ciudad"],
    quizCorrect: "больница",
    quizOptions: ["больница", "школа", "рынок", "парк"],
  },
  {
    language: "es",
    conceptKey: "bank",
    word: "banco",
    translationRu: "банк",
    type: "Place",
    rarity: "C",
    baseAtk: 40,
    baseDef: 65,
    colorido: 1,
    flavorText: "Tengo que ir al banco a sacar plata.",
    hint: "«Banco» почти как «банк»; слышится звон монет у стойки.",
    tags: ["dinero", "ciudad"],
    quizCorrect: "банк",
    quizOptions: ["банк", "магазин", "дом", "школа"],
  },
  {
    language: "es",
    conceptKey: "kitchen",
    word: "cocina",
    translationRu: "кухня",
    type: "Place",
    rarity: "C",
    baseAtk: 35,
    baseDef: 60,
    colorido: 2,
    flavorText: "La cocina está llena de olor a café.",
    hint: "«Cocina» — та же семья, что cook: место, где готовят, кухня.",
    tags: ["hogar", "básico"],
    quizCorrect: "кухня",
    quizOptions: ["кухня", "ванная", "улица", "офис"],
  },
  {
    language: "es",
    conceptKey: "bathroom",
    word: "baño",
    translationRu: "ванная",
    type: "Place",
    rarity: "C",
    baseAtk: 30,
    baseDef: 65,
    colorido: 1,
    flavorText: "Disculpá, ¿dónde queda el baño?",
    hint: "«Baño» похоже на «баню» — сразу вспоминается ванная.",
    tags: ["hogar", "básico"],
    quizCorrect: "ванная",
    quizOptions: ["ванная", "кухня", "спальня", "площадь"],
  },
  {
    language: "es",
    conceptKey: "square",
    word: "plaza",
    translationRu: "площадь",
    type: "Place",
    rarity: "C",
    baseAtk: 45,
    baseDef: 50,
    colorido: 2,
    flavorText: "Nos vemos en la plaza a las seis.",
    hint: "«Plaza» напоминает плац — открытая площадь.",
    tags: ["ciudad", "encuentros"],
    quizCorrect: "площадь",
    quizOptions: ["площадь", "улица", "район", "парк"],
  },

  // Persons (12)
  {
    language: "es",
    conceptKey: "friend",
    word: "amigo",
    translationRu: "друг",
    type: "Person",
    rarity: "C",
    baseAtk: 55,
    baseDef: 35,
    colorido: 2,
    flavorText: "—Che, ¿venís? —Sí, voy con un amigo.",
    hint: "«Amigo» — как «амиго» из фильмов: так и зовут друга.",
    tags: ["relaciones", "básico"],
    quizCorrect: "друг",
    quizOptions: ["друг", "враг", "сосед", "клиент"],
  },
  {
    language: "es",
    conceptKey: "mother",
    word: "madre",
    translationRu: "мама",
    type: "Person",
    rarity: "C",
    baseAtk: 45,
    baseDef: 60,
    colorido: 2,
    flavorText: "Mi madre cocina muy rico.",
    hint: "«Madre» напоминает слово «мать» — значит мама.",
    tags: ["familia", "básico"],
    quizCorrect: "мама",
    quizOptions: ["мама", "папа", "сестра", "дочь"],
  },
  {
    language: "es",
    conceptKey: "father",
    word: "padre",
    translationRu: "папа",
    type: "Person",
    rarity: "C",
    baseAtk: 45,
    baseDef: 60,
    colorido: 2,
    flavorText: "Mi padre trabaja todo el día.",
    hint: "«Padre» — знакомый «падре» из фильмов, то есть папа.",
    tags: ["familia", "básico"],
    quizCorrect: "папа",
    quizOptions: ["папа", "мама", "дядя", "сын"],
  },
  {
    language: "es",
    conceptKey: "brother",
    word: "hermano",
    translationRu: "брат",
    type: "Person",
    rarity: "C",
    baseAtk: 50,
    baseDef: 45,
    colorido: 2,
    flavorText: "Mi hermano siempre llega tarde.",
    hint: "«Hermano» — как «братан, hermano» в латино-фильмах: значит брат.",
    tags: ["familia", "básico"],
    quizCorrect: "брат",
    quizOptions: ["брат", "сестра", "друг", "сосед"],
  },
  {
    language: "es",
    conceptKey: "sister",
    word: "hermana",
    translationRu: "сестра",
    type: "Person",
    rarity: "C",
    baseAtk: 50,
    baseDef: 45,
    colorido: 2,
    flavorText: "Mi hermana estudia medicina.",
    hint: "«Hermana» — та же семейная пара с «hermano», только мягче: сестра.",
    tags: ["familia", "básico"],
    quizCorrect: "сестра",
    quizOptions: ["сестра", "брат", "мама", "учитель"],
  },
  {
    language: "es",
    conceptKey: "son",
    word: "hijo",
    translationRu: "сын",
    type: "Person",
    rarity: "C",
    baseAtk: 45,
    baseDef: 55,
    colorido: 2,
    flavorText: "Su hijo ya tiene cinco años.",
    hint: "«Hijo» звучит как короткое детское «хи-хо» — вспоминается сын.",
    tags: ["familia", "básico"],
    quizCorrect: "сын",
    quizOptions: ["сын", "дочь", "брат", "папа"],
  },
  {
    language: "es",
    conceptKey: "daughter",
    word: "hija",
    translationRu: "дочь",
    type: "Person",
    rarity: "C",
    baseAtk: 45,
    baseDef: 55,
    colorido: 2,
    flavorText: "Mi hija quiere un helado.",
    hint: "«Hija» — мягкое окончание, как ласковое обращение к дочери.",
    tags: ["familia", "básico"],
    quizCorrect: "дочь",
    quizOptions: ["дочь", "сын", "мама", "сестра"],
  },
  {
    language: "es",
    conceptKey: "doctor",
    word: "doctor",
    translationRu: "врач",
    type: "Person",
    rarity: "C",
    baseAtk: 55,
    baseDef: 45,
    colorido: 1,
    flavorText: "El doctor me dijo que descanse.",
    hint: "«Doctor» — чистый интернационализм: доктор и есть врач.",
    tags: ["salud", "profesiones"],
    quizCorrect: "врач",
    quizOptions: ["врач", "водитель", "повар", "учитель"],
  },
  {
    language: "es",
    conceptKey: "teacher",
    word: "profesor",
    translationRu: "учитель",
    type: "Person",
    rarity: "C",
    baseAtk: 55,
    baseDef: 45,
    colorido: 1,
    flavorText: "El profesor explica muy claro.",
    hint: "«Profesor» почти как «профессор», а значит учитель.",
    tags: ["educación", "profesiones"],
    quizCorrect: "учитель",
    quizOptions: ["учитель", "врач", "начальник", "сосед"],
  },
  {
    language: "es",
    conceptKey: "student",
    word: "estudiante",
    translationRu: "студент",
    type: "Person",
    rarity: "C",
    baseAtk: 50,
    baseDef: 50,
    colorido: 1,
    flavorText: "Soy estudiante y trabajo a medio tiempo.",
    hint: "«Estudiante» напоминает student — студент.",
    tags: ["educación", "básico"],
    quizCorrect: "студент",
    quizOptions: ["студент", "учитель", "врач", "клиент"],
  },
  {
    language: "es",
    conceptKey: "neighbor",
    word: "vecino",
    translationRu: "сосед",
    type: "Person",
    rarity: "C",
    baseAtk: 45,
    baseDef: 55,
    colorido: 2,
    flavorText: "Mi vecino pone música fuerte siempre.",
    hint: "«Vecino» звучит как «возле» — сосед живёт возле тебя.",
    tags: ["hogar", "relaciones"],
    quizCorrect: "сосед",
    quizOptions: ["сосед", "друг", "начальник", "учитель"],
  },
  {
    language: "es",
    conceptKey: "boy",
    word: "niño",
    translationRu: "мальчик",
    type: "Person",
    rarity: "C",
    baseAtk: 55,
    baseDef: 40,
    colorido: 2,
    flavorText: "El niño no quiere dormir.",
    hint: "«Niño» звучит нежно, как оклик маленькому мальчику.",
    tags: ["familia", "básico"],
    quizCorrect: "мальчик",
    quizOptions: ["мальчик", "девочка", "сын", "брат"],
  },
  {
    language: "es",
    conceptKey: "girl",
    word: "niña",
    translationRu: "девочка",
    type: "Person",
    rarity: "C",
    baseAtk: 55,
    baseDef: 40,
    colorido: 2,
    flavorText: "La niña está jugando en la plaza.",
    hint: "«Niña» с мягким «ня» в конце легко цепляется за девочку.",
    tags: ["familia", "básico"],
    quizCorrect: "девочка",
    quizOptions: ["девочка", "мальчик", "дочь", "сестра"],
  },

  // Actions (15)
  {
    language: "es",
    conceptKey: "eat",
    word: "comer",
    translationRu: "есть (кушать)",
    type: "Action",
    rarity: "C",
    baseAtk: 60,
    baseDef: 35,
    colorido: 2,
    flavorText: "Vamos a comer algo antes de salir.",
    hint: "«Comer» звучит как «ком еды» — значит есть.",
    tags: ["verbo", "comida"],
    quizCorrect: "есть (кушать)",
    quizOptions: ["есть (кушать)", "пить", "спать", "читать"],
  },
  {
    language: "es",
    conceptKey: "drink",
    word: "beber",
    translationRu: "пить",
    type: "Action",
    rarity: "C",
    baseAtk: 55,
    baseDef: 40,
    colorido: 1,
    flavorText: "No puedo beber café tan tarde.",
    hint: "«Beber» — как «буль-буль»: пить.",
    tags: ["verbo", "bebidas"],
    quizCorrect: "пить",
    quizOptions: ["пить", "есть (кушать)", "спать", "гулять"],
  },
  {
    language: "es",
    conceptKey: "sleep",
    word: "dormir",
    translationRu: "спать",
    type: "Action",
    rarity: "C",
    baseAtk: 40,
    baseDef: 65,
    colorido: 1,
    flavorText: "Hoy quiero dormir temprano.",
    hint: "«Dormir» напоминает dormitory — место, где спят.",
    tags: ["verbo", "rutina"],
    quizCorrect: "спать",
    quizOptions: ["спать", "есть (кушать)", "работать", "прыгать"],
  },
  {
    language: "es",
    conceptKey: "speak",
    word: "hablar",
    translationRu: "говорить",
    type: "Action",
    rarity: "C",
    baseAtk: 55,
    baseDef: 40,
    colorido: 2,
    flavorText: "Necesito hablar contigo un momento.",
    hint: "«Hablar» звучит будто «болтать» — значит говорить.",
    tags: ["verbo", "comunicación"],
    quizCorrect: "говорить",
    quizOptions: ["говорить", "слушать", "читать", "писать"],
  },
  {
    language: "es",
    conceptKey: "read",
    word: "leer",
    translationRu: "читать",
    type: "Action",
    rarity: "C",
    baseAtk: 50,
    baseDef: 45,
    colorido: 1,
    flavorText: "Me gusta leer por la noche.",
    hint: "«Leer» похоже на «лирику»: читаешь строки глазами.",
    tags: ["verbo", "ocio"],
    quizCorrect: "читать",
    quizOptions: ["читать", "писать", "слушать", "спать"],
  },
  {
    language: "es",
    conceptKey: "write",
    word: "escribir",
    translationRu: "писать",
    type: "Action",
    rarity: "C",
    baseAtk: 55,
    baseDef: 45,
    colorido: 1,
    flavorText: "¿Me podés escribir cuando llegues?",
    hint: "«Escribir» напоминает scribe — тот, кто пишет.",
    tags: ["verbo", "comunicación"],
    quizCorrect: "писать",
    quizOptions: ["писать", "читать", "говорить", "бегать"],
  },
  {
    language: "es",
    conceptKey: "go",
    word: "ir",
    translationRu: "идти / ехать",
    type: "Action",
    rarity: "C",
    baseAtk: 60,
    baseDef: 45,
    colorido: 2,
    flavorText: "¿Vamos al centro? Dale, vamos.",
    hint: "«Ir» короткое, как сам рывок: и раз — пошёл или поехал.",
    tags: ["verbo", "movimiento"],
    quizCorrect: "идти / ехать",
    quizOptions: ["идти / ехать", "приходить", "остаться", "смотреть"],
  },
  {
    language: "es",
    conceptKey: "come",
    word: "venir",
    translationRu: "приходить",
    type: "Action",
    rarity: "C",
    baseAtk: 55,
    baseDef: 45,
    colorido: 2,
    flavorText: "¿Venís a casa hoy o estás ocupado?",
    hint: "«Venir» будто зовёт «винир сюда» — прийти к кому-то.",
    tags: ["verbo", "movimiento"],
    quizCorrect: "приходить",
    quizOptions: ["приходить", "уходить", "спать", "покупать"],
  },
  {
    language: "es",
    conceptKey: "see",
    word: "ver",
    translationRu: "видеть",
    type: "Action",
    rarity: "C",
    baseAtk: 55,
    baseDef: 40,
    colorido: 1,
    flavorText: "No te veo desde hace meses.",
    hint: "«Ver» — как video: сначала видеть.",
    tags: ["verbo", "comunicación"],
    quizCorrect: "видеть",
    quizOptions: ["видеть", "слушать", "говорить", "прыгать"],
  },
  {
    language: "es",
    conceptKey: "do",
    word: "hacer",
    translationRu: "делать",
    type: "Action",
    rarity: "C",
    baseAtk: 60,
    baseDef: 45,
    colorido: 1,
    flavorText: "¿Qué querés hacer después?",
    hint: "«Hacer» звучит деятельно, как хасл: делать.",
    tags: ["verbo", "básico"],
    quizCorrect: "делать",
    quizOptions: ["делать", "говорить", "читать", "спать"],
  },
  {
    language: "es",
    conceptKey: "want",
    word: "querer",
    translationRu: "хотеть",
    type: "Action",
    rarity: "C",
    baseAtk: 60,
    baseDef: 40,
    colorido: 2,
    flavorText: "Quiero un té con limón, por favor.",
    hint: "«Querer» похоже на care: не всё равно, значит хотеть.",
    tags: ["verbo", "básico"],
    quizCorrect: "хотеть",
    quizOptions: ["хотеть", "мочь", "знать", "бояться"],
  },
  {
    language: "es",
    conceptKey: "need",
    word: "necesitar",
    translationRu: "нуждаться",
    type: "Action",
    rarity: "C",
    baseAtk: 55,
    baseDef: 50,
    colorido: 1,
    flavorText: "Necesito ayuda con esto.",
    hint: "«Necesitar» напоминает necessity — сильная нужда.",
    tags: ["verbo", "básico"],
    quizCorrect: "нуждаться",
    quizOptions: ["нуждаться", "покупать", "ждать", "терять / проигрывать"],
  },
  {
    language: "es",
    conceptKey: "think",
    word: "pensar",
    translationRu: "думать",
    type: "Action",
    rarity: "C",
    baseAtk: 50,
    baseDef: 55,
    colorido: 1,
    flavorText: "Déjame pensar un segundo.",
    hint: "«Pensar» — надел пенсне и начал думать.",
    tags: ["verbo", "básico"],
    quizCorrect: "думать",
    quizOptions: ["думать", "говорить", "видеть", "есть (кушать)"],
  },
  {
    language: "es",
    conceptKey: "play",
    word: "jugar",
    translationRu: "играть",
    type: "Action",
    rarity: "C",
    baseAtk: 55,
    baseDef: 40,
    colorido: 2,
    flavorText: "Los chicos quieren jugar afuera.",
    hint: "«Jugar» звучит азартно, как крик перед игрой.",
    tags: ["verbo", "tiempo_libre"],
    quizCorrect: "играть",
    quizOptions: ["играть", "читать", "спать", "плавать"],
  },
  {
    language: "es",
    conceptKey: "walk",
    word: "caminar",
    translationRu: "гулять / ходить пешком",
    type: "Action",
    rarity: "C",
    baseAtk: 45,
    baseDef: 55,
    colorido: 1,
    flavorText: "Prefiero caminar, no queda tan lejos.",
    hint: "«Caminar» — будто километры наматывать ногами: ходить пешком.",
    tags: ["verbo", "movimiento"],
    quizCorrect: "гулять / ходить пешком",
    quizOptions: ["гулять / ходить пешком", "бегать", "прыгать", "спать"],
  },

  // Objects (20)
  {
    language: "es",
    conceptKey: "water",
    word: "agua",
    translationRu: "вода",
    type: "Object",
    rarity: "C",
    baseAtk: 35,
    baseDef: 70,
    colorido: 1,
    flavorText: "¿Me das un vaso de agua, por favor?",
    hint: "«Agua» — родственница «аква»: аквариум и вода держат слово в памяти.",
    tags: ["bebidas", "básico"],
    quizCorrect: "вода",
    quizOptions: ["вода", "кофе", "молоко", "чай"],
  },
  {
    language: "es",
    conceptKey: "book",
    word: "libro",
    translationRu: "книга",
    type: "Object",
    rarity: "C",
    baseAtk: 45,
    baseDef: 55,
    colorido: 1,
    flavorText: "Este libro es muy interesante.",
    hint: "«Libro» напоминает «либретто» — тоже текст и книга.",
    tags: ["objetos", "educación"],
    quizCorrect: "книга",
    quizOptions: ["книга", "стол", "окно", "ключ"],
  },
  {
    language: "es",
    conceptKey: "table",
    word: "mesa",
    translationRu: "стол",
    type: "Object",
    rarity: "C",
    baseAtk: 30,
    baseDef: 75,
    colorido: 1,
    flavorText: "Dejá las llaves sobre la mesa.",
    hint: "«Mesa» звучит как место для тарелок — стол.",
    tags: ["hogar", "objetos"],
    quizCorrect: "стол",
    quizOptions: ["стол", "стул", "кровать", "дверь"],
  },
  {
    language: "es",
    conceptKey: "chair",
    word: "silla",
    translationRu: "стул",
    type: "Object",
    rarity: "C",
    baseAtk: 30,
    baseDef: 70,
    colorido: 1,
    flavorText: "Sentate en esa silla, por favor.",
    hint: "«Silla» — будто «сел-ла»: сел на стул.",
    tags: ["hogar", "objetos"],
    quizCorrect: "стул",
    quizOptions: ["стул", "стол", "кровать", "окно"],
  },
  {
    language: "es",
    conceptKey: "bed",
    word: "cama",
    translationRu: "кровать",
    type: "Object",
    rarity: "C",
    baseAtk: 25,
    baseDef: 80,
    colorido: 1,
    flavorText: "Me quedé dormido en la cama sin querer.",
    hint: "«Cama» мягко качает, как гамак, — значит кровать.",
    tags: ["hogar", "rutina"],
    quizCorrect: "кровать",
    quizOptions: ["кровать", "стул", "стол", "дверь"],
  },
  {
    language: "es",
    conceptKey: "door",
    word: "puerta",
    translationRu: "дверь",
    type: "Object",
    rarity: "C",
    baseAtk: 30,
    baseDef: 70,
    colorido: 1,
    flavorText: "Cerrá la puerta que entra frío.",
    hint: "«Puerta» напоминает portal: дверь как вход в дом.",
    tags: ["hogar", "objetos"],
    quizCorrect: "дверь",
    quizOptions: ["дверь", "окно", "ключ", "стена"],
  },
  {
    language: "es",
    conceptKey: "window",
    word: "ventana",
    translationRu: "окно",
    type: "Object",
    rarity: "C",
    baseAtk: 30,
    baseDef: 70,
    colorido: 1,
    flavorText: "Abrí la ventana un minuto, porfa.",
    hint: "«Ventana» связана с ветром и вентиляцией — окно.",
    tags: ["hogar", "objetos"],
    quizCorrect: "окно",
    quizOptions: ["окно", "дверь", "книга", "парк"],
  },
  {
    language: "es",
    conceptKey: "phone",
    word: "teléfono",
    translationRu: "телефон",
    type: "Object",
    rarity: "C",
    baseAtk: 50,
    baseDef: 50,
    colorido: 2,
    flavorText: "No encuentro mi teléfono, ¿lo viste?",
    hint: "«Teléfono» — это и есть телефон, слово почти одинаковое.",
    tags: ["tecnología", "básico"],
    quizCorrect: "телефон",
    quizOptions: ["телефон", "ключ", "кошелёк", "книга"],
  },
  {
    language: "es",
    conceptKey: "key",
    word: "llave",
    translationRu: "ключ",
    type: "Object",
    rarity: "C",
    baseAtk: 45,
    baseDef: 55,
    colorido: 1,
    flavorText: "Me olvidé la llave adentro, qué desastre.",
    hint: "«Llave» — как лязг ключей в кармане: ключ.",
    tags: ["hogar", "objetos"],
    quizCorrect: "ключ",
    quizOptions: ["ключ", "дверь", "окно", "телефон"],
  },
  {
    language: "es",
    conceptKey: "money",
    word: "dinero",
    translationRu: "деньги",
    type: "Object",
    rarity: "C",
    baseAtk: 55,
    baseDef: 45,
    colorido: 2,
    flavorText: "No tengo dinero ahora, te pago mañana.",
    hint: "«Dinero» напоминает dinar и денарий — всё про деньги.",
    tags: ["dinero", "básico"],
    quizCorrect: "деньги",
    quizOptions: ["деньги", "время", "еда", "книга"],
  },
  {
    language: "es",
    conceptKey: "food",
    word: "comida",
    translationRu: "еда",
    type: "Object",
    rarity: "C",
    baseAtk: 55,
    baseDef: 45,
    colorido: 2,
    flavorText: "La comida está lista, ¡vení!",
    hint: "«Comida» — как «ком еды»: значит еда.",
    tags: ["comida", "básico"],
    quizCorrect: "еда",
    quizOptions: ["еда", "вода", "деньги", "погода"],
  },
  {
    language: "es",
    conceptKey: "bread",
    word: "pan",
    translationRu: "хлеб",
    type: "Object",
    rarity: "C",
    baseAtk: 45,
    baseDef: 55,
    colorido: 1,
    flavorText: "Compré pan recién hecho.",
    hint: "«Pan» короткое и сытное, как кусок хлеба.",
    tags: ["comida", "básico"],
    quizCorrect: "хлеб",
    quizOptions: ["хлеб", "молоко", "яблоко", "курица"],
  },
  {
    language: "es",
    conceptKey: "milk",
    word: "leche",
    translationRu: "молоко",
    type: "Object",
    rarity: "C",
    baseAtk: 40,
    baseDef: 60,
    colorido: 1,
    flavorText: "¿Querés leche en el café?",
    hint: "«Leche» хочется выпить на ночь — молоко.",
    tags: ["bebidas", "comida"],
    quizCorrect: "молоко",
    quizOptions: ["молоко", "вода", "чай", "сок"],
  },
  {
    language: "es",
    conceptKey: "coffee",
    word: "café",
    translationRu: "кофе",
    type: "Object",
    rarity: "C",
    baseAtk: 55,
    baseDef: 40,
    colorido: 2,
    flavorText: "Necesito un café para arrancar el día.",
    hint: "«Café» — международное слово для кофе.",
    tags: ["bebidas", "rutina"],
    quizCorrect: "кофе",
    quizOptions: ["кофе", "чай", "вода", "молоко"],
  },
  {
    language: "es",
    conceptKey: "tea",
    word: "té",
    translationRu: "чай",
    type: "Object",
    rarity: "C",
    baseAtk: 45,
    baseDef: 50,
    colorido: 1,
    flavorText: "Me hago un té y me relajo un poco.",
    hint: "«Té» звучит как tea — чай.",
    tags: ["bebidas", "rutina"],
    quizCorrect: "чай",
    quizOptions: ["чай", "кофе", "вода", "сок"],
  },
  {
    language: "es",
    conceptKey: "apple",
    word: "manzana",
    translationRu: "яблоко",
    type: "Object",
    rarity: "C",
    baseAtk: 45,
    baseDef: 45,
    colorido: 2,
    flavorText: "Me llevo una manzana para el camino.",
    hint: "«Manzana» манит взять яблоко — так и запоминается.",
    tags: ["comida", "fruta"],
    quizCorrect: "яблоко",
    quizOptions: ["яблоко", "банан", "апельсин", "груша"],
  },
  {
    language: "es",
    conceptKey: "chicken",
    word: "pollo",
    translationRu: "курица",
    type: "Object",
    rarity: "C",
    baseAtk: 50,
    baseDef: 45,
    colorido: 1,
    flavorText: "Hoy comemos pollo con arroz.",
    hint: "«Pollo» — будто пёрышко полетело: курица.",
    tags: ["comida", "cocina"],
    quizCorrect: "курица",
    quizOptions: ["курица", "рыба", "мясо", "сыр"],
  },
  {
    language: "es",
    conceptKey: "clothes",
    word: "ropa",
    translationRu: "одежда",
    type: "Object",
    rarity: "C",
    baseAtk: 40,
    baseDef: 60,
    colorido: 1,
    flavorText: "Tengo que lavar la ropa hoy.",
    hint: "«Ropa» напоминает robe — одежда.",
    tags: ["hogar", "básico"],
    quizCorrect: "одежда",
    quizOptions: ["одежда", "еда", "вода", "книга"],
  },
  {
    language: "es",
    conceptKey: "shoes",
    word: "zapatos",
    translationRu: "обувь",
    type: "Object",
    rarity: "C",
    baseAtk: 35,
    baseDef: 65,
    colorido: 1,
    flavorText: "Me compré unos zapatos nuevos.",
    hint: "«Zapatos» звучит как «сапоги» на испанский лад — обувь.",
    tags: ["ropa", "compras"],
    quizCorrect: "обувь",
    quizOptions: ["обувь", "одежда", "шляпа", "куртка"],
  },
  {
    language: "es",
    conceptKey: "watch",
    word: "reloj",
    translationRu: "часы",
    type: "Object",
    rarity: "C",
    baseAtk: 40,
    baseDef: 60,
    colorido: 1,
    flavorText: "¿Tenés hora? Me olvidé el reloj.",
    hint: "«Reloj» тикает, как реле времени, — часы.",
    tags: ["tiempo", "básico"],
    quizCorrect: "часы",
    quizOptions: ["часы", "телефон", "ключ", "книга"],
  },

  // Emotions (10)
  {
    language: "es",
    conceptKey: "happy",
    word: "feliz",
    translationRu: "счастливый",
    type: "Emotion",
    rarity: "C",
    baseAtk: 55,
    baseDef: 45,
    colorido: 2,
    flavorText: "Estoy muy feliz hoy.",
    hint: "«Feliz» напоминает Феликса — счастливого кота.",
    tags: ["emociones", "básico"],
    quizCorrect: "счастливый",
    quizOptions: ["счастливый", "грустный", "злой", "уставший"],
  },
  {
    language: "es",
    conceptKey: "sad",
    word: "triste",
    translationRu: "грустный",
    type: "Emotion",
    rarity: "C",
    baseAtk: 50,
    baseDef: 50,
    colorido: 1,
    flavorText: "No estés triste, todo va a estar bien.",
    hint: "«Triste» — как Тристан, печальный герой.",
    tags: ["emociones", "básico"],
    quizCorrect: "грустный",
    quizOptions: ["грустный", "счастливый", "голодный", "спокойный"],
  },
  {
    language: "es",
    conceptKey: "tired",
    word: "cansado",
    translationRu: "уставший",
    type: "Emotion",
    rarity: "C",
    baseAtk: 40,
    baseDef: 60,
    colorido: 1,
    flavorText: "Estoy cansado, me voy a dormir.",
    hint: "«Cansado» — как «кончился заряд»: уставший.",
    tags: ["estado", "básico"],
    quizCorrect: "уставший",
    quizOptions: ["уставший", "счастливый", "злой", "смешной"],
  },
  {
    language: "es",
    conceptKey: "angry",
    word: "enojado",
    translationRu: "злой",
    type: "Emotion",
    rarity: "C",
    baseAtk: 60,
    baseDef: 40,
    colorido: 2,
    flavorText: "No te enojes, fue un chiste.",
    hint: "«Enojado» звучит резко и колюче — так и чувствуется злость.",
    tags: ["emociones", "básico"],
    quizCorrect: "злой",
    quizOptions: ["злой", "грустный", "спокойный", "уставший"],
  },
  {
    language: "es",
    conceptKey: "nervous",
    word: "nervioso",
    translationRu: "нервный",
    type: "Emotion",
    rarity: "C",
    baseAtk: 45,
    baseDef: 55,
    colorido: 1,
    flavorText: "Estoy nervioso por el examen.",
    hint: "«Nervioso» почти как «нервный» — значит нервный.",
    tags: ["emociones", "estudio"],
    quizCorrect: "нервный",
    quizOptions: ["нервный", "счастливый", "ленивый", "холодный"],
  },
  {
    language: "es",
    conceptKey: "calm",
    word: "tranquilo",
    translationRu: "спокойный",
    type: "Emotion",
    rarity: "C",
    baseAtk: 35,
    baseDef: 70,
    colorido: 1,
    flavorText: "Tranquilo, no pasa nada.",
    hint: "«Tranquilo» напоминает транквилизатор — спокойный.",
    tags: ["emociones", "conversación"],
    quizCorrect: "спокойный",
    quizOptions: ["спокойный", "нервный", "злой", "уставший"],
  },
  {
    language: "es",
    conceptKey: "bored",
    word: "aburrido",
    translationRu: "скучный / скучающий",
    type: "Emotion",
    rarity: "C",
    baseAtk: 40,
    baseDef: 55,
    colorido: 1,
    flavorText: "Estoy aburrido, hagamos algo.",
    hint: "«Aburrido» тянется скучно и вязко — скучный или скучающий.",
    tags: ["estado", "básico"],
    quizCorrect: "скучный / скучающий",
    quizOptions: ["скучный / скучающий", "счастливый", "голодный", "занятый"],
  },
  {
    language: "es",
    conceptKey: "pleased",
    word: "contento",
    translationRu: "довольный",
    type: "Emotion",
    rarity: "C",
    baseAtk: 50,
    baseDef: 45,
    colorido: 2,
    flavorText: "Estoy contento con el resultado.",
    hint: "«Contento» — будто контент зашёл, и ты доволен.",
    tags: ["emociones", "conversación"],
    quizCorrect: "довольный",
    quizOptions: ["довольный", "грустный", "злой", "нервный"],
  },
  {
    language: "es",
    conceptKey: "hungry",
    word: "hambriento",
    translationRu: "голодный",
    type: "Emotion",
    rarity: "C",
    baseAtk: 55,
    baseDef: 40,
    colorido: 1,
    flavorText: "Estoy hambriento, ¿pedimos algo?",
    hint: "«Hambriento» — как хомяк, который всё время хочет есть: голодный.",
    tags: ["estado", "comida"],
    quizCorrect: "голодный",
    quizOptions: ["голодный", "уставший", "счастливый", "спокойный"],
  },

  // Expressions (6)
  {
    language: "es",
    conceptKey: "hello",
    word: "hola",
    translationRu: "привет",
    type: "Expression",
    rarity: "C",
    baseAtk: 60,
    baseDef: 35,
    colorido: 2,
    flavorText: "Hola, ¿todo bien?",
    hint: "«Hola» — как короткое «ола!» при встрече: привет.",
    tags: ["saludos", "básico"],
    quizCorrect: "привет",
    quizOptions: ["привет", "пока", "спасибо", "пожалуйста"],
  },
  {
    language: "es",
    conceptKey: "goodbye",
    word: "adiós",
    translationRu: "пока",
    type: "Expression",
    rarity: "C",
    baseAtk: 55,
    baseDef: 40,
    colorido: 1,
    flavorText: "Bueno, me voy. ¡Adiós!",
    hint: "«Adiós» звучит как киношное «адьёс» — пока.",
    tags: ["saludos", "básico"],
    quizCorrect: "пока",
    quizOptions: ["пока", "привет", "спасибо", "извини"],
  },
  {
    language: "es",
    conceptKey: "thank_you",
    word: "gracias",
    translationRu: "спасибо",
    type: "Expression",
    rarity: "C",
    baseAtk: 55,
    baseDef: 50,
    colorido: 2,
    flavorText: "Gracias por ayudarme, posta.",
    hint: "«Gracias» хочется сказать с грацией — значит спасибо.",
    tags: ["cortesía", "básico"],
    quizCorrect: "спасибо",
    quizOptions: ["спасибо", "пожалуйста", "извини", "привет"],
  },
  {
    language: "es",
    conceptKey: "sorry",
    word: "lo siento",
    translationRu: "извини",
    type: "Expression",
    rarity: "C",
    baseAtk: 45,
    baseDef: 60,
    colorido: 1,
    flavorText: "Lo siento, llegué tarde.",
    hint: "«Siento» — как «сентимент»: мне жаль, извини.",
    tags: ["cortesía", "básico"],
    quizCorrect: "извини",
    quizOptions: ["извини", "спасибо", "пожалуйста", "пока"],
  },
  {
    language: "es",
    conceptKey: "how_are_you",
    word: "¿qué tal?",
    translationRu: "как дела?",
    type: "Expression",
    rarity: "C",
    baseAtk: 60,
    baseDef: 40,
    colorido: 2,
    flavorText: "—¡Hola! —¡Ey! ¿Qué tal?",
    hint: "«Qué tal?» звучит как «ну, как там?» — то есть как дела?",
    tags: ["conversación", "básico"],
    quizCorrect: "как дела?",
    quizOptions: ["как дела?", "спасибо", "до завтра", "ничего страшного"],
  },
  {
    language: "es",
    conceptKey: "good_morning",
    word: "buenos días",
    translationRu: "доброе утро",
    type: "Expression",
    rarity: "C",
    baseAtk: 55,
    baseDef: 45,
    colorido: 2,
    flavorText: "Buenos días, ¿me das un café?",
    hint: "«Buenos días» — как доброе «бон-утро» на весь день.",
    tags: ["saludos", "cortesía"],
    quizCorrect: "доброе утро",
    quizOptions: ["доброе утро", "добрый вечер", "спокойной ночи", "как дела?"],
  },
];

