import type { SeedWord } from "./seed-words.types.js";

export const UNCOMMON_WORDS: SeedWord[] = [
  // Places (7)
  {
    language: "es",
    conceptKey: "office",
    word: "oficina",
    translationRu: "офис",
    type: "Place",
    rarity: "UC",
    baseAtk: 45,
    baseDef: 65,
    colorido: 2,
    flavorText: "Hoy me toca ir a la oficina, qué fiaca.",
    hint: "«Oficina» похожа на office — офис.",
    tags: ["trabajo", "ciudad"],
    quizCorrect: "офис",
    quizOptions: ["офис", "школа", "больница", "ресторан"],
  },
  {
    language: "es",
    conceptKey: "restaurant",
    word: "restaurante",
    translationRu: "ресторан",
    type: "Place",
    rarity: "UC",
    baseAtk: 55,
    baseDef: 55,
    colorido: 3,
    flavorText: "Ese restaurante es carísimo, pero se come increíble.",
    hint: "«Restaurante» почти как ресторан — легко держится в памяти.",
    tags: ["comida", "salidas"],
    quizCorrect: "ресторан",
    quizOptions: ["ресторан", "магазин", "банк", "станция"],
  },
  {
    language: "es",
    conceptKey: "airport",
    word: "aeropuerto",
    translationRu: "аэропорт",
    type: "Place",
    rarity: "UC",
    baseAtk: 55,
    baseDef: 60,
    colorido: 2,
    flavorText: "Llegamos al aeropuerto con dos horas de margen.",
    hint: "«Aeropuerto» = aero + puerto, воздушный порт, аэропорт.",
    tags: ["viajes", "transporte"],
    quizCorrect: "аэропорт",
    quizOptions: ["аэропорт", "площадь", "офис", "дом"],
  },
  {
    language: "es",
    conceptKey: "station",
    word: "estación",
    translationRu: "станция",
    type: "Place",
    rarity: "UC",
    baseAtk: 45,
    baseDef: 65,
    colorido: 2,
    flavorText: "Bajate en la próxima estación y caminá dos cuadras.",
    hint: "«Estación» напоминает station — станция.",
    tags: ["transporte", "ciudad"],
    quizCorrect: "станция",
    quizOptions: ["станция", "аэропорт", "парк", "школа"],
  },
  {
    language: "es",
    conceptKey: "river",
    word: "río",
    translationRu: "река",
    type: "Place",
    rarity: "UC",
    baseAtk: 50,
    baseDef: 55,
    colorido: 3,
    flavorText: "Nos sentamos al lado del río a tomar mate.",
    hint: "«Río» течёт коротко и звонко — как река.",
    tags: ["naturaleza", "paseo"],
    quizCorrect: "река",
    quizOptions: ["река", "гора", "лес", "пустыня"],
  },
  {
    language: "es",
    conceptKey: "mountain",
    word: "montaña",
    translationRu: "гора",
    type: "Place",
    rarity: "UC",
    baseAtk: 55,
    baseDef: 55,
    colorido: 3,
    flavorText: "La montaña se ve increíble desde acá.",
    hint: "«Montaña» похожа на mountain — гора.",
    tags: ["naturaleza", "viajes"],
    quizCorrect: "гора",
    quizOptions: ["гора", "река", "пляж", "город"],
  },
  {
    language: "es",
    conceptKey: "supermarket",
    word: "supermercado",
    translationRu: "супермаркет",
    type: "Place",
    rarity: "UC",
    baseAtk: 50,
    baseDef: 60,
    colorido: 2,
    flavorText: "Paso por el supermercado y compro algo para cenar.",
    hint: "«Supermercado» — это super + mercado, значит супермаркет.",
    tags: ["compras", "comida"],
    quizCorrect: "супермаркет",
    quizOptions: ["супермаркет", "школа", "банк", "аэропорт"],
  },

  // Persons (8)
  {
    language: "es",
    conceptKey: "boss",
    word: "jefe",
    translationRu: "начальник",
    type: "Person",
    rarity: "UC",
    baseAtk: 65,
    baseDef: 55,
    colorido: 3,
    flavorText: "Mi jefe quiere hablar conmigo después.",
    hint: "«Jefe» звучит как шеф — начальник.",
    tags: ["trabajo", "profesiones"],
    quizCorrect: "начальник",
    quizOptions: ["начальник", "учитель", "сосед", "клиент"],
  },
  {
    language: "es",
    conceptKey: "coworker",
    word: "compañero",
    translationRu: "коллега",
    type: "Person",
    rarity: "UC",
    baseAtk: 55,
    baseDef: 60,
    colorido: 2,
    flavorText: "Un compañero del laburo me cubrió el turno.",
    hint: "«Compañero» напоминает companion — тот, кто рядом, коллега.",
    tags: ["trabajo", "relaciones"],
    quizCorrect: "коллега",
    quizOptions: ["коллега", "начальник", "клиент", "врач"],
  },
  {
    language: "es",
    conceptKey: "client",
    word: "cliente",
    translationRu: "клиент",
    type: "Person",
    rarity: "UC",
    baseAtk: 55,
    baseDef: 55,
    colorido: 2,
    flavorText: "El cliente pidió un cambio a último momento.",
    hint: "«Cliente» почти как клиент — интернационализм.",
    tags: ["trabajo", "servicios"],
    quizCorrect: "клиент",
    quizOptions: ["клиент", "коллега", "сосед", "ученик"],
  },
  {
    language: "es",
    conceptKey: "driver",
    word: "conductor",
    translationRu: "водитель",
    type: "Person",
    rarity: "UC",
    baseAtk: 60,
    baseDef: 55,
    colorido: 2,
    flavorText: "El conductor frenó de golpe y casi me caigo.",
    hint: "«Conductor» — будто кондуктор за рулём, значит водитель.",
    tags: ["transporte", "profesiones"],
    quizCorrect: "водитель",
    quizOptions: ["водитель", "врач", "повар", "полицейский"],
  },
  {
    language: "es",
    conceptKey: "cook_person",
    word: "cocinero",
    translationRu: "повар",
    type: "Person",
    rarity: "UC",
    baseAtk: 60,
    baseDef: 50,
    colorido: 3,
    flavorText: "El cocinero hizo una salsa espectacular.",
    hint: "«Cocinero» живёт рядом с cocina, значит повар.",
    tags: ["comida", "profesiones"],
    quizCorrect: "повар",
    quizOptions: ["повар", "врач", "водитель", "клиент"],
  },
  {
    language: "es",
    conceptKey: "nurse",
    word: "enfermera",
    translationRu: "медсестра",
    type: "Person",
    rarity: "UC",
    baseAtk: 50,
    baseDef: 65,
    colorido: 2,
    flavorText: "La enfermera me tomó la presión.",
    hint: "«Enfermera» связана с enfermo, больным: рядом с ним медсестра.",
    tags: ["salud", "profesiones"],
    quizCorrect: "медсестра",
    quizOptions: ["медсестра", "учитель", "клиент", "сосед"],
  },
  {
    language: "es",
    conceptKey: "police_officer",
    word: "policía",
    translationRu: "полицейский",
    type: "Person",
    rarity: "UC",
    baseAtk: 65,
    baseDef: 55,
    colorido: 2,
    flavorText: "Un policía me pidió el documento.",
    hint: "«Policía» почти как полиция — полицейский.",
    tags: ["ciudad", "profesiones"],
    quizCorrect: "полицейский",
    quizOptions: ["полицейский", "водитель", "повар", "начальник"],
  },
  {
    language: "es",
    conceptKey: "artist",
    word: "artista",
    translationRu: "артист",
    type: "Person",
    rarity: "UC",
    baseAtk: 60,
    baseDef: 50,
    colorido: 3,
    flavorText: "Ese artista pinta murales por toda la ciudad.",
    hint: "«Artista» — артист и есть, слово почти не меняется.",
    tags: ["cultura", "profesiones"],
    quizCorrect: "артист",
    quizOptions: ["артист", "врач", "учитель", "клиент"],
  },

  // Actions (10)
  {
    language: "es",
    conceptKey: "run",
    word: "correr",
    translationRu: "бегать",
    type: "Action",
    rarity: "UC",
    baseAtk: 65,
    baseDef: 45,
    colorido: 2,
    flavorText: "Me gusta correr por el parque a la mañana.",
    hint: "«Correr» напоминает корриду — там все бегают.",
    tags: ["deporte", "verbo"],
    quizCorrect: "бегать",
    quizOptions: ["бегать", "гулять / ходить пешком", "плавать", "спать"],
  },
  {
    language: "es",
    conceptKey: "listen",
    word: "escuchar",
    translationRu: "слушать",
    type: "Action",
    rarity: "UC",
    baseAtk: 55,
    baseDef: 60,
    colorido: 2,
    flavorText: "¿Podés escucharme un segundo?",
    hint: "«Escuchar» — как «слух включить»: слушать.",
    tags: ["comunicación", "verbo"],
    quizCorrect: "слушать",
    quizOptions: ["слушать", "говорить", "читать", "писать"],
  },
  {
    language: "es",
    conceptKey: "cook_action",
    word: "cocinar",
    translationRu: "готовить (еду)",
    type: "Action",
    rarity: "UC",
    baseAtk: 60,
    baseDef: 50,
    colorido: 3,
    flavorText: "Hoy me toca cocinar para todos.",
    hint: "«Cocinar» — делать магию на cocina, то есть готовить.",
    tags: ["comida", "verbo"],
    quizCorrect: "готовить (еду)",
    quizOptions: ["готовить (еду)", "покупать", "читать", "ждать"],
  },
  {
    language: "es",
    conceptKey: "drive",
    word: "conducir",
    translationRu: "водить (машину)",
    type: "Action",
    rarity: "UC",
    baseAtk: 60,
    baseDef: 55,
    colorido: 2,
    flavorText: "No puedo conducir de noche, me cansa.",
    hint: "«Conducir» напоминает conduct — вести, значит водить.",
    tags: ["transporte", "verbo"],
    quizCorrect: "водить (машину)",
    quizOptions: ["водить (машину)", "плавать", "бегать", "спать"],
  },
  {
    language: "es",
    conceptKey: "buy",
    word: "comprar",
    translationRu: "покупать",
    type: "Action",
    rarity: "UC",
    baseAtk: 60,
    baseDef: 45,
    colorido: 2,
    flavorText: "Tengo que comprar verduras para la cena.",
    hint: "«Comprar» звучит как «купи прямо» — покупать.",
    tags: ["compras", "verbo"],
    quizCorrect: "покупать",
    quizOptions: ["покупать", "продавать", "искать", "ждать"],
  },
  {
    language: "es",
    conceptKey: "sell",
    word: "vender",
    translationRu: "продавать",
    type: "Action",
    rarity: "UC",
    baseAtk: 55,
    baseDef: 50,
    colorido: 2,
    flavorText: "Quiero vender la bici porque no la uso.",
    hint: "«Vender» напоминает vendor — продавать.",
    tags: ["compras", "verbo"],
    quizCorrect: "продавать",
    quizOptions: ["продавать", "покупать", "искать", "выигрывать"],
  },
  {
    language: "es",
    conceptKey: "call",
    word: "llamar",
    translationRu: "звонить",
    type: "Action",
    rarity: "UC",
    baseAtk: 60,
    baseDef: 50,
    colorido: 2,
    flavorText: "Te llamo en cinco, estoy saliendo.",
    hint: "«Llamar» — будто крик «алло, Мар!» в трубку: звонить.",
    tags: ["comunicación", "verbo"],
    quizCorrect: "звонить",
    quizOptions: ["звонить", "писать", "читать", "спать"],
  },
  {
    language: "es",
    conceptKey: "wait",
    word: "esperar",
    translationRu: "ждать",
    type: "Action",
    rarity: "UC",
    baseAtk: 45,
    baseDef: 65,
    colorido: 1,
    flavorText: "Esperá un toque, ya vuelvo.",
    hint: "«Esperar» — как «сперва постой»: ждать.",
    tags: ["verbo", "conversación"],
    quizCorrect: "ждать",
    quizOptions: ["ждать", "идти / ехать", "терять / проигрывать", "спать"],
  },
  {
    language: "es",
    conceptKey: "search",
    word: "buscar",
    translationRu: "искать",
    type: "Action",
    rarity: "UC",
    baseAtk: 55,
    baseDef: 55,
    colorido: 2,
    flavorText: "Estoy buscando mis lentes por todos lados.",
    hint: "«Buscar» — будто обыскать всё вокруг, значит искать.",
    tags: ["verbo", "básico"],
    quizCorrect: "искать",
    quizOptions: ["искать", "находить", "ждать", "покупать"],
  },
  {
    language: "es",
    conceptKey: "learn",
    word: "aprender",
    translationRu: "учиться",
    type: "Action",
    rarity: "UC",
    baseAtk: 55,
    baseDef: 60,
    colorido: 2,
    flavorText: "Estoy aprendiendo español de a poco.",
    hint: "«Aprender» напоминает apprentice — тот, кто учится.",
    tags: ["estudio", "verbo"],
    quizCorrect: "учиться",
    quizOptions: ["учиться", "работать", "спать", "терять / проигрывать"],
  },

  // Objects (10)
  {
    language: "es",
    conceptKey: "work_noun",
    word: "trabajo",
    translationRu: "работа",
    type: "Object",
    rarity: "UC",
    baseAtk: 55,
    baseDef: 60,
    colorido: 2,
    flavorText: "Tengo mucho trabajo esta semana.",
    hint: "«Trabajo» — как вечный трабл, который и есть работа.",
    tags: ["trabajo", "vida"],
    quizCorrect: "работа",
    quizOptions: ["работа", "школа", "путешествие", "парк"],
  },
  {
    language: "es",
    conceptKey: "trip",
    word: "viaje",
    translationRu: "путешествие",
    type: "Object",
    rarity: "UC",
    baseAtk: 60,
    baseDef: 55,
    colorido: 3,
    flavorText: "Este viaje fue increíble, quiero repetir.",
    hint: "«Viaje» напоминает voyage — путешествие.",
    tags: ["viajes", "vida"],
    quizCorrect: "путешествие",
    quizOptions: ["путешествие", "встреча (совещание)", "работа", "страх"],
  },
  {
    language: "es",
    conceptKey: "ticket",
    word: "boleto",
    translationRu: "билет",
    type: "Object",
    rarity: "UC",
    baseAtk: 50,
    baseDef: 55,
    colorido: 2,
    flavorText: "Compré el boleto para mañana.",
    hint: "«Boleto» звучит как билетик в дорогу — билет.",
    tags: ["transporte", "viajes"],
    quizCorrect: "билет",
    quizOptions: ["билет", "паспорт", "карта", "подарок"],
  },
  {
    language: "es",
    conceptKey: "map",
    word: "mapa",
    translationRu: "карта",
    type: "Object",
    rarity: "UC",
    baseAtk: 45,
    baseDef: 60,
    colorido: 2,
    flavorText: "Sin mapa me pierdo seguro.",
    hint: "«Mapa» почти как map — карта.",
    tags: ["viajes", "básico"],
    quizCorrect: "карта",
    quizOptions: ["карта", "билет", "ключ", "телефон"],
  },
  {
    language: "es",
    conceptKey: "computer",
    word: "computadora",
    translationRu: "компьютер",
    type: "Object",
    rarity: "UC",
    baseAtk: 60,
    baseDef: 55,
    colorido: 2,
    flavorText: "Mi computadora anda lenta hoy.",
    hint: "«Computadora» — компьютер с испанским окончанием.",
    tags: ["tecnología", "vida"],
    quizCorrect: "компьютер",
    quizOptions: ["компьютер", "телефон", "книга", "часы"],
  },
  {
    language: "es",
    conceptKey: "bicycle",
    word: "bicicleta",
    translationRu: "велосипед",
    type: "Object",
    rarity: "UC",
    baseAtk: 55,
    baseDef: 50,
    colorido: 3,
    flavorText: "Voy en bicicleta porque es más rápido.",
    hint: "«Bicicleta» напоминает bicycle — велосипед.",
    tags: ["transporte", "deporte"],
    quizCorrect: "велосипед",
    quizOptions: ["велосипед", "машина", "автобус", "самолёт"],
  },
  {
    language: "es",
    conceptKey: "backpack",
    word: "mochila",
    translationRu: "рюкзак",
    type: "Object",
    rarity: "UC",
    baseAtk: 50,
    baseDef: 55,
    colorido: 2,
    flavorText: "Metí la botella en la mochila.",
    hint: "«Mochila» звучит мягко, как мешок за спиной, — рюкзак.",
    tags: ["viajes", "objetos"],
    quizCorrect: "рюкзак",
    quizOptions: ["рюкзак", "сумка", "кошелёк", "пальто"],
  },
  {
    language: "es",
    conceptKey: "gift",
    word: "regalo",
    translationRu: "подарок",
    type: "Object",
    rarity: "UC",
    baseAtk: 55,
    baseDef: 50,
    colorido: 3,
    flavorText: "Te traje un regalo chiquito.",
    hint: "«Regalo» — как regal, королевский дар: подарок.",
    tags: ["fiesta", "relaciones"],
    quizCorrect: "подарок",
    quizOptions: ["подарок", "билет", "паспорт", "карта"],
  },
  {
    language: "es",
    conceptKey: "passport",
    word: "pasaporte",
    translationRu: "паспорт",
    type: "Object",
    rarity: "UC",
    baseAtk: 45,
    baseDef: 65,
    colorido: 2,
    flavorText: "No te olvides el pasaporte, por las dudas.",
    hint: "«Pasaporte» = pass + porte, пропуск через границу, паспорт.",
    tags: ["viajes", "documentos"],
    quizCorrect: "паспорт",
    quizOptions: ["паспорт", "билет", "ключ", "телефон"],
  },
  {
    language: "es",
    conceptKey: "medicine",
    word: "medicina",
    translationRu: "лекарство",
    type: "Object",
    rarity: "UC",
    baseAtk: 40,
    baseDef: 70,
    colorido: 1,
    flavorText: "Tomé la medicina y me sentí mejor.",
    hint: "«Medicina» почти как медицина, а значит лекарство.",
    tags: ["salud", "básico"],
    quizCorrect: "лекарство",
    quizOptions: ["лекарство", "еда", "вода", "подарок"],
  },

  // Emotions (6)
  {
    language: "es",
    conceptKey: "fear",
    word: "miedo",
    translationRu: "страх",
    type: "Emotion",
    rarity: "UC",
    baseAtk: 60,
    baseDef: 50,
    colorido: 2,
    flavorText: "Tengo miedo de la oscuridad.",
    hint: "«Miedo» звучит так, будто сердце ёкнуло, — страх.",
    tags: ["emociones", "básico"],
    quizCorrect: "страх",
    quizOptions: ["страх", "радость", "грусть", "сюрприз"],
  },
  {
    language: "es",
    conceptKey: "joy",
    word: "alegría",
    translationRu: "радость",
    type: "Emotion",
    rarity: "UC",
    baseAtk: 55,
    baseDef: 60,
    colorido: 3,
    flavorText: "Fue una noticia llena de alegría.",
    hint: "«Alegría» — лёгкое и сияющее слово, как сама радость.",
    tags: ["emociones", "vida"],
    quizCorrect: "радость",
    quizOptions: ["радость", "страх", "злость", "грусть"],
  },
  {
    language: "es",
    conceptKey: "surprise_emotion",
    word: "sorpresa",
    translationRu: "сюрприз",
    type: "Emotion",
    rarity: "UC",
    baseAtk: 55,
    baseDef: 55,
    colorido: 3,
    flavorText: "Te tengo una sorpresa, pero no mires todavía.",
    hint: "«Sorpresa» — словно коробка внезапно раскрылась: сюрприз.",
    tags: ["emociones", "relaciones"],
    quizCorrect: "сюрприз",
    quizOptions: ["сюрприз", "страх", "радость", "стыд"],
  },
  {
    language: "es",
    conceptKey: "embarrassment",
    word: "vergüenza",
    translationRu: "стыд",
    type: "Emotion",
    rarity: "UC",
    baseAtk: 50,
    baseDef: 65,
    colorido: 2,
    flavorText: "Me da vergüenza hablar en público.",
    hint: "«Vergüenza» звучит неловко и запутанно — как само чувство стыда.",
    tags: ["emociones", "comunicación"],
    quizCorrect: "стыд",
    quizOptions: ["стыд", "страх", "радость", "спокойствие"],
  },
  {
    language: "es",
    conceptKey: "worry",
    word: "preocupación",
    translationRu: "беспокойство",
    type: "Emotion",
    rarity: "UC",
    baseAtk: 45,
    baseDef: 70,
    colorido: 2,
    flavorText: "Tuve una preocupación y no pude dormir.",
    hint: "«Preocupación» — как preoccupation: голова занята, значит беспокойство.",
    tags: ["emociones", "vida"],
    quizCorrect: "беспокойство",
    quizOptions: ["беспокойство", "радость", "сюрприз", "скука"],
  },
  {
    language: "es",
    conceptKey: "patience",
    word: "paciencia",
    translationRu: "терпение",
    type: "Emotion",
    rarity: "UC",
    baseAtk: 40,
    baseDef: 75,
    colorido: 2,
    flavorText: "Tené paciencia, ya va a salir.",
    hint: "«Paciencia» напоминает patient — терпение.",
    tags: ["emociones", "conversación"],
    quizCorrect: "терпение",
    quizOptions: ["терпение", "страх", "радость", "стыд"],
  },

  // Expressions (4)
  {
    language: "es",
    conceptKey: "please",
    word: "por favor",
    translationRu: "пожалуйста",
    type: "Expression",
    rarity: "UC",
    baseAtk: 50,
    baseDef: 65,
    colorido: 2,
    flavorText: "Un café, por favor.",
    hint: "«Por favor» — будто просишь по-фаворски, очень вежливо: пожалуйста.",
    tags: ["cortesía", "básico"],
    quizCorrect: "пожалуйста",
    quizOptions: ["пожалуйста", "спасибо", "извини", "пока"],
  },
  {
    language: "es",
    conceptKey: "you_are_welcome",
    word: "de nada",
    translationRu: "не за что",
    type: "Expression",
    rarity: "UC",
    baseAtk: 45,
    baseDef: 65,
    colorido: 2,
    flavorText: "—Gracias. —De nada, no fue nada.",
    hint: "«De nada» буквально «да это ничего» — не за что.",
    tags: ["cortesía", "conversación"],
    quizCorrect: "не за что",
    quizOptions: ["не за что", "пожалуйста", "извини", "как дела?"],
  },
  {
    language: "es",
    conceptKey: "excuse_me",
    word: "permiso",
    translationRu: "разрешите",
    type: "Expression",
    rarity: "UC",
    baseAtk: 45,
    baseDef: 60,
    colorido: 2,
    flavorText: "Permiso, ¿puedo pasar?",
    hint: "«Permiso» напоминает permission — разрешите.",
    tags: ["cortesía", "ciudad"],
    quizCorrect: "разрешите",
    quizOptions: ["разрешите", "спасибо", "пока", "осторожно"],
  },
  {
    language: "es",
    conceptKey: "how_nice",
    word: "¡qué lindo!",
    translationRu: "как красиво!",
    type: "Expression",
    rarity: "UC",
    baseAtk: 55,
    baseDef: 45,
    colorido: 3,
    flavorText: "¡Qué lindo lugar! Quiero sacar una foto.",
    hint: "«Qué lindo!» — как восторженное «какая милота!» — как красиво!",
    tags: ["conversación", "emociones"],
    quizCorrect: "как красиво!",
    quizOptions: ["как красиво!", "как дела?", "не за что", "доброе утро"],
  },
];


